# Cours 6 - Data collection

**Objectifs du cours:**
- explorer les bases du web scraping avec python
- connaitre les principales ressources pour trouver des datasets
- choisir un dataset sur lequel le projet sera effectué

## Les ressouces pour trouver des datasets

Je vous invite à consulter la liste (non exhaustive) des sites suivants pour avoir une idée des datasets que vous pouvez trouver en ligne.

- https://www.data.gouv.fr/fr/
- https://www.kaggle.com/datasets
- https://www.data.gov
- https://github.com/awesomedata/awesome-public-datasets
- https://data.gov.uk
- https://worlddata.ai/partners/kdnuggets
- https://github.com/niderhoff/nlp-datasets
- https://opendata.paris.fr/pages/home/

**Exercice:** En voyant la diversité des datasets qui existent et pour vous aider à faire votre choix essayez de vous poser les questions suivantes:
- Quels domaines m'intéressent le plus (Biologie, Sport, Economie, etc ...) ?
- Avec quels types de variables est ce que j'aimerais travailler (texte, catégories, numériques, dates, ...) ?
- Est ce qu'il y a une ou des questions particulières que j'aimerais explorer ?

## Introduction au web scraping

Comme exemple, voyons comment j'ai fait pour récupérer les donnés pour construire pays.sql

Les données viennent du suite suivant: http://doheth.co.uk/info/countries-of-the-world.php

Nous allons utiliser 2 librairies différentes: `requests`, pour faire une requete http vers notre site, et `BeautifulSoup`, pour récupérer le html de notre site.

In [1]:
import requests
from bs4 import BeautifulSoup

URL = "http://doheth.co.uk/info/countries-of-the-world.php"
page = requests.get(URL)

soup = BeautifulSoup(page.content, "html.parser")

In [2]:
soup

<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8"/>
<title>Countries of the World ~ capital cities, populations, sizes and more</title>
<link href="/info/geography.css" rel="stylesheet"/>
<meta content="List of all countries in the world with capital cities and more details." name="description"/>
<script src="/js/jquery.js"></script>
<script src="/js/jquery.tablesorter.js"></script>
<script src="/js/jquery.tablesorter.parsers.js"></script>
<script>
$(document).ready(function(){
	// sort table; disable sorting on currency
	$("#countries").tablesorter({
		sortList: [[0,0]],
		headers: { 3:{sorter:false}, 4:{sorter:'num'}, 5:{sorter:'num'}, 6:{sorter:'num'}, 7:{sorter:'num'}, 8:{sorter:'num'}, 9:{sorter:'num'}, 10:{sorter:'num'} }
	})
});
</script>
</head>
<body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1974891-1', 'doheth.co.uk');
  ga('send', 'pageview');
</script>
<h1>Country profiles</h1>
<div class="content">
<p>The following table lists all recognised sovereign states in the world
		with detailed information, including capital city, currencies,
		population, land area, population density, birth rate, death rate and
		Gross Domestic Product (GDP).</p>
<p>You can also click a column heading to instantly sort by that column.</p>
<p>Also available: <a href="us-states.php">United States of America profiles</a></p>
</div>
<table class="data" id="countries">
<thead>
<tr>
<th>Name<br/>
<small>(English)</small></th>
<th>Location<br/>
<small>(Continent)</small></th>
<th>Capital city<br/>
<small>(official)</small></th>
<th>Currency<br/>
<small>(poss. multiple)</small></th>
<th>Population<br/>
<small>(inhabitants)</small></th>
<th>Area<br/>
<small>(km²)</small></th>
<th>Pop. density<br/>
<small>(inhabitants/km²)</small></th>
<th>GDP (nominal)<br/>
<small>(millions of USD)</small></th>
<th>Life exp.<br/>
<small>(years)</small></th>
<th>Birth rate<br/>
<small>(births/1,000)</small></th>
<th>Death rate<br/>
<small>(deaths/1,000)</small></th>
</tr>
</thead>
<tbody>
<tr>
<td class="name">Abkhazia</td>
<td>Asia<br/>
<small>(Central West)</small></td>
<td>Sukhumi</td>
<td>Georgian lari;<br/>Russian ruble</td>
<td class="numeric">216,000</td>
<td class="numeric">8,600</td>
<td class="numeric">25</td>
<td class="numeric">-</td>
<td class="numeric">-</td>
<td class="numeric">-</td>
<td class="numeric">-</td>
</tr>
<tr>
<td class="name">Afghanistan</td>
<td>Asia<br/>
<small>(Central)</small></td>
<td>Kabul</td>
<td>Afghan afghani</td>
<td class="numeric">29,863,010</td>
<td class="numeric">652,090</td>
<td class="numeric">46</td>
<td class="numeric">7,168</td>
<td class="numeric">42.90</td>
<td class="numeric">46.60</td>
<td class="numeric">20.75</td>
</tr>
<tr>
<td class="name">Albania</td>
<td>Europe<br/>
<small>(South East)</small></td>
<td>Tirana</td>
<td>Albanian lek</td>
<td class="numeric">3,129,678</td>
<td class="numeric">28,748</td>
<td class="numeric">109</td>
<td class="numeric">8,379</td>
<td class="numeric">77.24</td>
<td class="numeric">15.11</td>
<td class="numeric">5.12</td>
</tr>
<tr>
<td class="name">Algeria</td>
<td>Africa<br/>
<small>(North Central)</small></td>
<td>Algiers</td>
<td>Algerian dinar</td>
<td class="numeric">32,853,800</td>
<td class="numeric">2,381,741</td>
<td class="numeric">13</td>
<td class="numeric">102,257</td>
<td class="numeric">73.00</td>
<td class="numeric">17.14</td>
<td class="numeric">4.60</td>
</tr>
<tr>
<td class="name">Andorra</td>
<td>Europe<br/>
<small>(South West)</small></td>
<td>Andorra la Vella</td>
<td>Euro</td>
<td class="numeric">67,151</td>
<td class="numeric">468</td>
<td class="numeric">143</td>
<td class="numeric">960</td>
<td class="numeric">83.51</td>
<td class="numeric">8.71</td>
<td class="numeric">6.07</td>
</tr>
<tr>
<td class="name">Angola</td>
<td>Africa<br/>
<small>(South West)</small></td>
<td>Luanda</td>
<td>Angolan kwanza</td>
<td class="numeric">15,941,390</td>
<td class="numeric">1,246,700</td>
<td class="numeric">12</td>
<td class="numeric">28,038</td>
<td class="numeric">38.43</td>
<td class="numeric">45.11</td>
<td class="numeric">24.50</td>
</tr>
<tr>
<td class="name">Antigua and Barbuda</td>
<td>North America<br/>
<small>(South East)</small></td>
<td>St. John's</td>
<td>East Caribbean dollar</td>
<td class="numeric">81,479</td>
<td class="numeric">442</td>
<td class="numeric">184</td>
<td class="numeric">905</td>
<td class="numeric">71.90</td>
<td class="numeric">16.93</td>
<td class="numeric">5.44</td>
</tr>
<tr>
<td class="name">Argentina</td>
<td>South America<br/>
<small>(South East)</small></td>
<td>Buenos Aires</td>
<td>Argentine peso</td>
<td class="numeric">38,747,150</td>
<td class="numeric">2,780,400</td>
<td class="numeric">13</td>
<td class="numeric">183,309</td>
<td class="numeric">75.91</td>
<td class="numeric">16.73</td>
<td class="numeric">7.56</td>
</tr>
<tr>
<td class="name">Armenia</td>
<td>Asia<br/>
<small>(Central West)</small></td>
<td>Yerevan</td>
<td>Armenian dram</td>
<td class="numeric">3,016,312</td>
<td class="numeric">29,800</td>
<td class="numeric">101</td>
<td class="numeric">4,903</td>
<td class="numeric">71.55</td>
<td class="numeric">12.07</td>
<td class="numeric">8.16</td>
</tr>
<tr>
<td class="name">Australia</td>
<td>Oceana<br/>
<small>(South West)</small></td>
<td>Canberra</td>
<td>Australian dollar</td>
<td class="numeric">20,155,130</td>
<td class="numeric">7,741,220</td>
<td class="numeric">2</td>
<td class="numeric">700,672</td>
<td class="numeric">81.01</td>
<td class="numeric">12.14</td>
<td class="numeric">7.44</td>
</tr>
<tr>
<td class="name">Austria</td>
<td>Europe<br/>
<small>(South Central)</small></td>
<td>Vienna</td>
<td>Euro</td>
<td class="numeric">8,189,444</td>
<td class="numeric">83,858</td>
<td class="numeric">98</td>
<td class="numeric">304,527</td>
<td class="numeric">79.07</td>
<td class="numeric">8.74</td>
<td class="numeric">9.70</td>
</tr>
<tr>
<td class="name">Azerbaijan</td>
<td>Asia<br/>
<small>(Central West)</small></td>
<td>Baku</td>
<td>Azerbaijani manat</td>
<td class="numeric">8,410,801</td>
<td class="numeric">86,600</td>
<td class="numeric">97</td>
<td class="numeric">12,561</td>
<td class="numeric">63.35</td>
<td class="numeric">20.74</td>
<td class="numeric">9.86</td>
</tr>
<tr>
<td class="name">Bahamas</td>
<td>North America<br/>
<small>(South East)</small></td>
<td>Nassau</td>
<td>Bahamian dollar</td>
<td class="numeric">323,063</td>
<td class="numeric">13,878</td>
<td class="numeric">23</td>
<td class="numeric">5,502</td>
<td class="numeric">65.54</td>
<td class="numeric">17.57</td>
<td class="numeric">8.97</td>
</tr>
<tr>
<td class="name">Bahrain</td>
<td>Asia<br/>
<small>(South West)</small></td>
<td>Manama</td>
<td>Bahraini dinar</td>
<td class="numeric">726,617</td>
<td class="numeric">694</td>
<td class="numeric">1,047</td>
<td class="numeric">12,995</td>
<td class="numeric">74.23</td>
<td class="numeric">17.80</td>
<td class="numeric">4.08</td>
</tr>
<tr>
<td class="name">Bangladesh</td>
<td>Asia<br/>
<small>(South Central)</small></td>
<td>Dhaka</td>
<td>Bangladeshi taka</td>
<td class="numeric">141,822,300</td>
<td class="numeric">143,998</td>
<td class="numeric">985</td>
<td class="numeric">59,958</td>
<td class="numeric">62.08</td>
<td class="numeric">29.80</td>
<td class="numeric">8.40</td>
</tr>
<tr>
<td class="name">Barbados</td>
<td>North America<br/>
<small>(South East)</small></td>
<td>Bridgetown</td>
<td>Barbadian dollar</td>
<td class="numeric">269,556</td>
<td class="numeric">430</td>
<td class="numeric">627</td>
<td class="numeric">2,976</td>
<td class="numeric">72.59</td>
<td class="numeric">12.71</td>
<td class="numeric">8.74</td>
</tr>
<tr>
<td class="name">Belarus</td>
<td>Europe<br/>
<small>(Central East)</small></td>
<td>Minsk</td>
<td>Belarusian ruble</td>
<td class="numeric">9,755,106</td>
<td class="numeric">207,600</td>
<td class="numeric">47</td>
<td class="numeric">29,566</td>
<td class="numeric">68.72</td>
<td class="numeric">11.16</td>
<td class="numeric">14.15</td>
</tr>
<tr>
<td class="name">Belgium</td>
<td>Europe<br/>
<small>(Central West)</small></td>
<td>Brussels</td>
<td>Euro</td>
<td class="numeric">10,419,050</td>
<td class="numeric">30,528</td>
<td class="numeric">341</td>
<td class="numeric">364,735</td>
<td class="numeric">78.77</td>
<td class="numeric">10.38</td>
<td class="numeric">10.22</td>
</tr>
<tr>
<td class="name">Belize</td>
<td>North America<br/>
<small>(South East)</small></td>
<td>Belmopan</td>
<td>Belize dollar</td>
<td class="numeric">269,736</td>
<td class="numeric">22,966</td>
<td class="numeric">11</td>
<td class="numeric">1,105</td>
<td class="numeric">68.44</td>
<td class="numeric">28.84</td>
<td class="numeric">5.65</td>
</tr>
<tr>
<td class="name">Benin</td>
<td>Africa<br/>
<small>(North West)</small></td>
<td>Cotonou</td>
<td>West African CFA franc</td>
<td class="numeric">8,438,853</td>
<td class="numeric">112,622</td>
<td class="numeric">75</td>
<td class="numeric">4,287</td>
<td class="numeric">52.66</td>
<td class="numeric">38.85</td>
<td class="numeric">12.49</td>
</tr>
<tr>
<td class="name">Bhutan</td>
<td>Asia<br/>
<small>(South Central)</small></td>
<td>Thimphu</td>
<td>Bhutanese ngultrum;<br/>Indian rupee</td>
<td class="numeric">2,162,546</td>
<td class="numeric">47,000</td>
<td class="numeric">46</td>
<td class="numeric">840</td>
<td class="numeric">54.39</td>
<td class="numeric">33.65</td>
<td class="numeric">12.94</td>
</tr>
<tr>
<td class="name">Bolivia</td>
<td>South America<br/>
<small>(Central)</small></td>
<td>La Paz</td>
<td>Bolivian boliviano</td>
<td class="numeric">9,182,015</td>
<td class="numeric">1,098,581</td>
<td class="numeric">8</td>
<td class="numeric">9,334</td>
<td class="numeric">65.50</td>
<td class="numeric">23.30</td>
<td class="numeric">7.64</td>
</tr>
<tr>
<td class="name">Bosnia and Herzegovina</td>
<td>Europe<br/>
<small>(South East)</small></td>
<td>Sarajevo</td>
<td>Convertible mark</td>
<td class="numeric">3,907,074</td>
<td class="numeric">51,197</td>
<td class="numeric">76</td>
<td class="numeric">9,369</td>
<td class="numeric">78.00</td>
<td class="numeric">8.77</td>
<td class="numeric">8.08</td>
</tr>
<tr>
<td class="name">Botswana</td>
<td>Africa<br/>
<small>(South Central)</small></td>
<td>Gaborone</td>
<td>Botswana pula</td>
<td class="numeric">1,764,926</td>
<td class="numeric">581,730</td>
<td class="numeric">3</td>
<td class="numeric">9,350</td>
<td class="numeric">33.87</td>
<td class="numeric">23.08</td>
<td class="numeric">29.36</td>
</tr>
<tr>
<td class="name">Brazil</td>
<td>South America<br/>
<small>(North East)</small></td>
<td>Brasília</td>
<td>Brazilian real</td>
<td class="numeric">186,404,900</td>
<td class="numeric">8,514,877</td>
<td class="numeric">22</td>
<td class="numeric">794,098</td>
<td class="numeric">71.69</td>
<td class="numeric">16.56</td>
<td class="numeric">6.15</td>
</tr>
<tr>
<td class="name">Brunei</td>
<td>Asia<br/>
<small>(South East)</small></td>
<td>Bandar Seri Begawan</td>
<td>Brunei dollar;<br/>Singapore dollar</td>
<td class="numeric">373,819</td>
<td class="numeric">5,765</td>
<td class="numeric">65</td>
<td class="numeric">9,531</td>
<td class="numeric">74.80</td>
<td class="numeric">18.79</td>
<td class="numeric">3.42</td>
</tr>
<tr>
<td class="name">Bulgaria</td>
<td>Europe<br/>
<small>(South East)</small></td>
<td>Sofia</td>
<td>Bulgarian lev</td>
<td class="numeric">7,725,965</td>
<td class="numeric">110,912</td>
<td class="numeric">70</td>
<td class="numeric">26,648</td>
<td class="numeric">72.03</td>
<td class="numeric">9.65</td>
<td class="numeric">14.26</td>
</tr>
<tr>
<td class="name">Burkina Faso</td>
<td>Africa<br/>
<small>(North West)</small></td>
<td>Ouagadougou</td>
<td>West African CFA franc</td>
<td class="numeric">13,227,840</td>
<td class="numeric">274,000</td>
<td class="numeric">48</td>
<td class="numeric">5,171</td>
<td class="numeric">48.45</td>
<td class="numeric">45.62</td>
<td class="numeric">15.92</td>
</tr>
<tr>
<td class="name">Burundi</td>
<td>Africa<br/>
<small>(Central East)</small></td>
<td>Bujumbura</td>
<td>Burundian franc</td>
<td class="numeric">7,547,515</td>
<td class="numeric">27,834</td>
<td class="numeric">271</td>
<td class="numeric">800</td>
<td class="numeric">50.29</td>
<td class="numeric">42.22</td>
<td class="numeric">13.79</td>
</tr>
<tr>
<td class="name">Cambodia</td>
<td>Asia<br/>
<small>(South East)</small></td>
<td>Phnom Penh</td>
<td>Cambodian riel</td>
<td class="numeric">14,071,010</td>
<td class="numeric">181,035</td>
<td class="numeric">78</td>
<td class="numeric">5,391</td>
<td class="numeric">58.92</td>
<td class="numeric">26.90</td>
<td class="numeric">9.15</td>
</tr>
<tr>
<td class="name">Cameroon</td>
<td>Africa<br/>
<small>(Central West)</small></td>
<td>Yaoundé</td>
<td>Central African CFA franc</td>
<td class="numeric">16,321,860</td>
<td class="numeric">475,442</td>
<td class="numeric">34</td>
<td class="numeric">16,985</td>
<td class="numeric">50.89</td>
<td class="numeric">33.89</td>
<td class="numeric">13.63</td>
</tr>
<tr>
<td class="name">Canada</td>
<td>North America<br/>
<small>(North Central)</small></td>
<td>Ottawa</td>
<td>Canadian dollar</td>
<td class="numeric">32,268,240</td>
<td class="numeric">9,970,610</td>
<td class="numeric">3</td>
<td class="numeric">1,115,192</td>
<td class="numeric">80.22</td>
<td class="numeric">10.78</td>
<td class="numeric">7.73</td>
</tr>
<tr>
<td class="name">Cape Verde</td>
<td>Africa<br/>
<small>(North West)</small></td>
<td>Praia</td>
<td>Cape Verdean escudo</td>
<td class="numeric">506,807</td>
<td class="numeric">4,033</td>
<td class="numeric">126</td>
<td class="numeric">1,024</td>
<td class="numeric">70.45</td>
<td class="numeric">24.87</td>
<td class="numeric">6.62</td>
</tr>
<tr>
<td class="name">Central African Republic</td>
<td>Africa<br/>
<small>(Central)</small></td>
<td>Bangui</td>
<td>Central African CFA franc</td>
<td class="numeric">4,037,747</td>
<td class="numeric">622,984</td>
<td class="numeric">6</td>
<td class="numeric">1,369</td>
<td class="numeric">43.39</td>
<td class="numeric">33.91</td>
<td class="numeric">18.81</td>
</tr>
<tr>
<td class="name">Chad</td>
<td>Africa<br/>
<small>(North Central)</small></td>
<td>N'Djamena</td>
<td>Central African CFA franc</td>
<td class="numeric">9,748,931</td>
<td class="numeric">1,284,000</td>
<td class="numeric">7</td>
<td class="numeric">5,469</td>
<td class="numeric">47.18</td>
<td class="numeric">45.73</td>
<td class="numeric">16.71</td>
</tr>
<tr>
<td class="name">Chile</td>
<td>South America<br/>
<small>(South West)</small></td>
<td>Valparaíso</td>
<td>Chilean peso</td>
<td class="numeric">16,295,100</td>
<td class="numeric">756,096</td>
<td class="numeric">22</td>
<td class="numeric">115,248</td>
<td class="numeric">76.58</td>
<td class="numeric">15.23</td>
<td class="numeric">5.76</td>
</tr>
<tr>
<td class="name">China, People's Republic of</td>
<td>Asia<br/>
<small>(Central East)</small></td>
<td>Beijing</td>
<td>Chinese yuan (renminbi)</td>
<td class="numeric">1,315,844,000</td>
<td class="numeric">9,596,961</td>
<td class="numeric">137</td>
<td class="numeric">2,228,862</td>
<td class="numeric">72.27</td>
<td class="numeric">13.25</td>
<td class="numeric">6.94</td>
</tr>
<tr>
<td class="name">Colombia</td>
<td>South America<br/>
<small>(North West)</small></td>
<td>Bogotá</td>
<td>Colombian peso</td>
<td class="numeric">45,600,240</td>
<td class="numeric">1,138,914</td>
<td class="numeric">40</td>
<td class="numeric">122,309</td>
<td class="numeric">71.72</td>
<td class="numeric">20.48</td>
<td class="numeric">5.59</td>
</tr>
<tr>
<td class="name">Comoros</td>
<td>Africa<br/>
<small>(South East)</small></td>
<td>Moroni</td>
<td>Comorian franc</td>
<td class="numeric">797,902</td>
<td class="numeric">2,235</td>
<td class="numeric">357</td>
<td class="numeric">382</td>
<td class="numeric">61.96</td>
<td class="numeric">36.93</td>
<td class="numeric">8.40</td>
</tr>
<tr>
<td class="name">Congo, Democratic Republic of the</td>
<td>Africa<br/>
<small>(Central)</small></td>
<td>Kinshasa</td>
<td>Congolese franc</td>
<td class="numeric">57,548,740</td>
<td class="numeric">2,344,858</td>
<td class="numeric">25</td>
<td class="numeric">6,974</td>
<td class="numeric">51.10</td>
<td class="numeric">43.69</td>
<td class="numeric">13.54</td>
</tr>
<tr>
<td class="name">Congo, Republic of the</td>
<td>Africa<br/>
<small>(Central West)</small></td>
<td>Brazzaville</td>
<td>Central African CFA franc</td>
<td class="numeric">3,998,904</td>
<td class="numeric">342,000</td>
<td class="numeric">11</td>
<td class="numeric">5,091</td>
<td class="numeric">52.26</td>
<td class="numeric">42.57</td>
<td class="numeric">13.30</td>
</tr>
<tr>
<td class="name">Costa Rica</td>
<td>North America<br/>
<small>(South East)</small></td>
<td>San José</td>
<td>Costa Rican colón</td>
<td class="numeric">4,327,228</td>
<td class="numeric">51,100</td>
<td class="numeric">85</td>
<td class="numeric">19,432</td>
<td class="numeric">76.84</td>
<td class="numeric">18.32</td>
<td class="numeric">4.33</td>
</tr>
<tr>
<td class="name">Croatia</td>
<td>Europe<br/>
<small>(South East)</small></td>
<td>Zagreb</td>
<td>Croatian kuna</td>
<td class="numeric">4,551,338</td>
<td class="numeric">56,538</td>
<td class="numeric">81</td>
<td class="numeric">37,412</td>
<td class="numeric">74.45</td>
<td class="numeric">9.61</td>
<td class="numeric">11.38</td>
</tr>
<tr>
<td class="name">Cuba</td>
<td>North America<br/>
<small>(South East)</small></td>
<td>Havana</td>
<td>Cuban convertible peso;<br/>Cuban peso</td>
<td class="numeric">11,269,400</td>
<td class="numeric">110,861</td>
<td class="numeric">102</td>
<td class="numeric">19,356</td>
<td class="numeric">77.23</td>
<td class="numeric">11.89</td>
<td class="numeric">7.19</td>
</tr>
<tr>
<td class="name">Cyprus</td>
<td>Asia<br/>
<small>(Central West)</small></td>
<td>Nicosia</td>
<td>Cypriot pound</td>
<td class="numeric">264,172</td>
<td class="numeric">3,355</td>
<td class="numeric">78</td>
<td class="numeric">15,418</td>
<td class="numeric">77.82</td>
<td class="numeric">12.56</td>
<td class="numeric">7.64</td>
</tr>
<tr>
<td class="name">Czech Republic</td>
<td>Europe<br/>
<small>(Central)</small></td>
<td>Prague</td>
<td>Czech koruna</td>
<td class="numeric">10,219,600</td>
<td class="numeric">78,866</td>
<td class="numeric">130</td>
<td class="numeric">122,345</td>
<td class="numeric">76.02</td>
<td class="numeric">10.40</td>
<td class="numeric">10.54</td>
</tr>
<tr>
<td class="name">Denmark</td>
<td>Europe<br/>
<small>(North Central)</small></td>
<td>Copenhagen</td>
<td>Danish krone</td>
<td class="numeric">5,430,590</td>
<td class="numeric">43,094</td>
<td class="numeric">126</td>
<td class="numeric">254,401</td>
<td class="numeric">77.79</td>
<td class="numeric">11.13</td>
<td class="numeric">10.43</td>
</tr>
<tr>
<td class="name">Djibouti</td>
<td>Africa<br/>
<small>(North East)</small></td>
<td>Djibouti City</td>
<td>Djiboutian franc</td>
<td class="numeric">793,078</td>
<td class="numeric">23,200</td>
<td class="numeric">34</td>
<td class="numeric">702</td>
<td class="numeric">43.10</td>
<td class="numeric">39.53</td>
<td class="numeric">19.39</td>
</tr>
<tr>
<td class="name">Dominica</td>
<td>North America<br/>
<small>(South East)</small></td>
<td>Roseau</td>
<td>East Caribbean dollar</td>
<td class="numeric">78,940</td>
<td class="numeric">751</td>
<td class="numeric">105</td>
<td class="numeric">279</td>
<td class="numeric">74.65</td>
<td class="numeric">15.27</td>
<td class="numeric">6.81</td>
</tr>
<tr>
<td class="name">Dominican Republic</td>
<td>North America<br/>
<small>(South East)</small></td>

Nous voyons en inspectant le code source que les informations des pays se situent dans les balises `tr`.

In [3]:
all_data= soup.find_all("tr")
all_data

[<tr>
 <th>Name<br/>
 <small>(English)</small></th>
 <th>Location<br/>
 <small>(Continent)</small></th>
 <th>Capital city<br/>
 <small>(official)</small></th>
 <th>Currency<br/>
 <small>(poss. multiple)</small></th>
 <th>Population<br/>
 <small>(inhabitants)</small></th>
 <th>Area<br/>
 <small>(km²)</small></th>
 <th>Pop. density<br/>
 <small>(inhabitants/km²)</small></th>
 <th>GDP (nominal)<br/>
 <small>(millions of USD)</small></th>
 <th>Life exp.<br/>
 <small>(years)</small></th>
 <th>Birth rate<br/>
 <small>(births/1,000)</small></th>
 <th>Death rate<br/>
 <small>(deaths/1,000)</small></th>
 </tr>,
 <tr>
 <td class="name">Abkhazia</td>
 <td>Asia<br/>
 <small>(Central West)</small></td>
 <td>Sukhumi</td>
 <td>Georgian lari;<br/>Russian ruble</td>
 <td class="numeric">216,000</td>
 <td class="numeric">8,600</td>
 <td class="numeric">25</td>
 <td class="numeric">-</td>
 <td class="numeric">-</td>
 <td class="numeric">-</td>
 <td class="numeric">-</td>
 </tr>,
 <tr>
 <td class="name">Afghanistan</td>
 <td>Asia<br/>
 <small>(Central)</small></td>
 <td>Kabul</td>
 <td>Afghan afghani</td>
 <td class="numeric">29,863,010</td>
 <td class="numeric">652,090</td>
 <td class="numeric">46</td>
 <td class="numeric">7,168</td>
 <td class="numeric">42.90</td>
 <td class="numeric">46.60</td>
 <td class="numeric">20.75</td>
 </tr>,
 <tr>
 <td class="name">Albania</td>
 <td>Europe<br/>
 <small>(South East)</small></td>
 <td>Tirana</td>
 <td>Albanian lek</td>
 <td class="numeric">3,129,678</td>
 <td class="numeric">28,748</td>
 <td class="numeric">109</td>
 <td class="numeric">8,379</td>
 <td class="numeric">77.24</td>
 <td class="numeric">15.11</td>
 <td class="numeric">5.12</td>
 </tr>,
 <tr>
 <td class="name">Algeria</td>
 <td>Africa<br/>
 <small>(North Central)</small></td>
 <td>Algiers</td>
 <td>Algerian dinar</td>
 <td class="numeric">32,853,800</td>
 <td class="numeric">2,381,741</td>
 <td class="numeric">13</td>
 <td class="numeric">102,257</td>
 <td class="numeric">73.00</td>
 <td class="numeric">17.14</td>
 <td class="numeric">4.60</td>
 </tr>,
 <tr>
 <td class="name">Andorra</td>
 <td>Europe<br/>
 <small>(South West)</small></td>
 <td>Andorra la Vella</td>
 <td>Euro</td>
 <td class="numeric">67,151</td>
 <td class="numeric">468</td>
 <td class="numeric">143</td>
 <td class="numeric">960</td>
 <td class="numeric">83.51</td>
 <td class="numeric">8.71</td>
 <td class="numeric">6.07</td>
 </tr>,
 <tr>
 <td class="name">Angola</td>
 <td>Africa<br/>
 <small>(South West)</small></td>
 <td>Luanda</td>
 <td>Angolan kwanza</td>
 <td class="numeric">15,941,390</td>
 <td class="numeric">1,246,700</td>
 <td class="numeric">12</td>
 <td class="numeric">28,038</td>
 <td class="numeric">38.43</td>
 <td class="numeric">45.11</td>
 <td class="numeric">24.50</td>
 </tr>,
 <tr>
 <td class="name">Antigua and Barbuda</td>
 <td>North America<br/>
 <small>(South East)</small></td>
 <td>St. John's</td>
 <td>East Caribbean dollar</td>
 <td class="numeric">81,479</td>
 <td class="numeric">442</td>
 <td class="numeric">184</td>
 <td class="numeric">905</td>
 <td class="numeric">71.90</td>
 <td class="numeric">16.93</td>
 <td class="numeric">5.44</td>
 </tr>,
 <tr>
 <td class="name">Argentina</td>
 <td>South America<br/>
 <small>(South East)</small></td>
 <td>Buenos Aires</td>
 <td>Argentine peso</td>
 <td class="numeric">38,747,150</td>
 <td class="numeric">2,780,400</td>
 <td class="numeric">13</td>
 <td class="numeric">183,309</td>
 <td class="numeric">75.91</td>
 <td class="numeric">16.73</td>
 <td class="numeric">7.56</td>
 </tr>,
 <tr>
 <td class="name">Armenia</td>
 <td>Asia<br/>
 <small>(Central West)</small></td>
 <td>Yerevan</td>
 <td>Armenian dram</td>
 <td class="numeric">3,016,312</td>
 <td class="numeric">29,800</td>
 <td class="numeric">101</td>
 <td class="numeric">4,903</td>
 <td class="numeric">71.55</td>
 <td class="numeric">12.07</td>
 <td class="numeric">8.16</td>
 </tr>,
 <tr>
 <td class="name">Australia</td>
 <td>Oceana<br/>
 <small>(South West)</small></td>
 <td>Canberra</td>
 <td>Australian dollar</td>
 <td class="numeric">20,155,130</td>
 <td class="numeric">7,741,220</td>
 <td class="numeric">2</td>
 <td class="numeric">700,672</td>
 <td class="numeric">81.01</td>
 <td class="numeric">12.14</td>
 <td class="numeric">7.44</td>
 </tr>,
 <tr>
 <td class="name">Austria</td>
 <td>Europe<br/>
 <small>(South Central)</small></td>
 <td>Vienna</td>
 <td>Euro</td>
 <td class="numeric">8,189,444</td>
 <td class="numeric">83,858</td>
 <td class="numeric">98</td>
 <td class="numeric">304,527</td>
 <td class="numeric">79.07</td>
 <td class="numeric">8.74</td>
 <td class="numeric">9.70</td>
 </tr>,
 <tr>
 <td class="name">Azerbaijan</td>
 <td>Asia<br/>
 <small>(Central West)</small></td>
 <td>Baku</td>
 <td>Azerbaijani manat</td>
 <td class="numeric">8,410,801</td>
 <td class="numeric">86,600</td>
 <td class="numeric">97</td>
 <td class="numeric">12,561</td>
 <td class="numeric">63.35</td>
 <td class="numeric">20.74</td>
 <td class="numeric">9.86</td>
 </tr>,
 <tr>
 <td class="name">Bahamas</td>
 <td>North America<br/>
 <small>(South East)</small></td>
 <td>Nassau</td>
 <td>Bahamian dollar</td>
 <td class="numeric">323,063</td>
 <td class="numeric">13,878</td>
 <td class="numeric">23</td>
 <td class="numeric">5,502</td>
 <td class="numeric">65.54</td>
 <td class="numeric">17.57</td>
 <td class="numeric">8.97</td>
 </tr>,
 <tr>
 <td class="name">Bahrain</td>
 <td>Asia<br/>
 <small>(South West)</small></td>
 <td>Manama</td>
 <td>Bahraini dinar</td>
 <td class="numeric">726,617</td>
 <td class="numeric">694</td>
 <td class="numeric">1,047</td>
 <td class="numeric">12,995</td>
 <td class="numeric">74.23</td>
 <td class="numeric">17.80</td>
 <td class="numeric">4.08</td>
 </tr>,
 <tr>
 <td class="name">Bangladesh</td>
 <td>Asia<br/>
 <small>(South Central)</small></td>
 <td>Dhaka</td>
 <td>Bangladeshi taka</td>
 <td class="numeric">141,822,300</td>
 <td class="numeric">143,998</td>
 <td class="numeric">985</td>
 <td class="numeric">59,958</td>
 <td class="numeric">62.08</td>
 <td class="numeric">29.80</td>
 <td class="numeric">8.40</td>
 </tr>,
 <tr>
 <td class="name">Barbados</td>
 <td>North America<br/>
 <small>(South East)</small></td>
 <td>Bridgetown</td>
 <td>Barbadian dollar</td>
 <td class="numeric">269,556</td>
 <td class="numeric">430</td>
 <td class="numeric">627</td>
 <td class="numeric">2,976</td>
 <td class="numeric">72.59</td>
 <td class="numeric">12.71</td>
 <td class="numeric">8.74</td>
 </tr>,
 <tr>
 <td class="name">Belarus</td>
 <td>Europe<br/>
 <small>(Central East)</small></td>
 <td>Minsk</td>
 <td>Belarusian ruble</td>
 <td class="numeric">9,755,106</td>
 <td class="numeric">207,600</td>
 <td class="numeric">47</td>
 <td class="numeric">29,566</td>
 <td class="numeric">68.72</td>
 <td class="numeric">11.16</td>
 <td class="numeric">14.15</td>
 </tr>,
 <tr>
 <td class="name">Belgium</td>
 <td>Europe<br/>
 <small>(Central West)</small></td>
 <td>Brussels</td>
 <td>Euro</td>
 <td class="numeric">10,419,050</td>
 <td class="numeric">30,528</td>
 <td class="numeric">341</td>
 <td class="numeric">364,735</td>
 <td class="numeric">78.77</td>
 <td class="numeric">10.38</td>
 <td class="numeric">10.22</td>
 </tr>,
 <tr>
 <td class="name">Belize</td>
 <td>North America<br/>
 <small>(South East)</small></td>
 <td>Belmopan</td>
 <td>Belize dollar</td>
 <td class="numeric">269,736</td>
 <td class="numeric">22,966</td>
 <td class="numeric">11</td>
 <td class="numeric">1,105</td>
 <td class="numeric">68.44</td>
 <td class="numeric">28.84</td>
 <td class="numeric">5.65</td>
 </tr>,
 <tr>
 <td class="name">Benin</td>
 <td>Africa<br/>
 <small>(North West)</small></td>
 <td>Cotonou</td>
 <td>West African CFA franc</td>
 <td class="numeric">8,438,853</td>
 <td class="numeric">112,622</td>
 <td class="numeric">75</td>
 <td class="numeric">4,287</td>
 <td class="numeric">52.66</td>
 <td class="numeric">38.85</td>
 <td class="numeric">12.49</td>
 </tr>,
 <tr>
 <td class="name">Bhutan</td>
 <td>Asia<br/>
 <small>(South Central)</small></td>
 <td>Thimphu</td>
 <td>Bhutanese ngultrum;<br/>Indian rupee</td>
 <td class="numeric">2,162,546</td>
 <td class="numeric">47,000</td>
 <td class="numeric">46</td>
 <td class="numeric">840</td>
 <td class="numeric">54.39</td>
 <td class="numeric">33.65</td>
 <td class="numeric">12.94</td>
 </tr>,
 <tr>
 <td class="name">Bolivia</td>
 <td>South America<br/>
 <small>(Central)</small></td>
 <td>La Paz</td>
 <td>Bolivian boliviano</td>
 <td class="numeric">9,182,015</td>
 <td class="numeric">1,098,581</td>
 <td class="numeric">8</td>
 <td class="numeric">9,334</td>
 <td class="numeric">65.50</td>
 <td class="numeric">23.30</td>
 <td class="numeric">7.64</td>
 </tr>,
 <tr>
 <td class="name">Bosnia and Herzegovina</td>
 <td>Europe<br/>
 <small>(South East)</small></td>
 <td>Sarajevo</td>
 <td>Convertible mark</td>
 <td class="numeric">3,907,074</td>
 <td class="numeric">51,197</td>
 <td class="numeric">76</td>
 <td class="numeric">9,369</td>
 <td class="numeric">78.00</td>
 <td class="numeric">8.77</td>
 <td class="numeric">8.08</td>
 </tr>,
 <tr>
 <td class="name">Botswana</td>
 <td>Africa<br/>
 <small>(South Central)</small></td>
 <td>Gaborone</td>
 <td>Botswana pula</td>
 <td class="numeric">1,764,926</td>
 <td class="numeric">581,730</td>
 <td class="numeric">3</td>
 <td class="numeric">9,350</td>
 <td class="numeric">33.87</td>
 <td class="numeric">23.08</td>
 <td class="numeric">29.36</td>
 </tr>,
 <tr>
 <td class="name">Brazil</td>
 <td>South America<br/>
 <small>(North East)</small></td>
 <td>Brasília</td>
 <td>Brazilian real</td>
 <td class="numeric">186,404,900</td>
 <td class="numeric">8,514,877</td>
 <td class="numeric">22</td>
 <td class="numeric">794,098</td>
 <td class="numeric">71.69</td>
 <td class="numeric">16.56</td>
 <td class="numeric">6.15</td>
 </tr>,
 <tr>
 <td class="name">Brunei</td>
 <td>Asia<br/>
 <small>(South East)</small></td>
 <td>Bandar Seri Begawan</td>
 <td>Brunei dollar;<br/>Singapore dollar</td>
 <td class="numeric">373,819</td>
 <td class="numeric">5,765</td>
 <td class="numeric">65</td>
 <td class="numeric">9,531</td>
 <td class="numeric">74.80</td>
 <td class="numeric">18.79</td>
 <td class="numeric">3.42</td>
 </tr>,
 <tr>
 <td class="name">Bulgaria</td>
 <td>Europe<br/>
 <small>(South East)</small></td>
 <td>Sofia</td>
 <td>Bulgarian lev</td>
 <td class="numeric">7,725,965</td>
 <td class="numeric">110,912</td>
 <td class="numeric">70</td>
 <td class="numeric">26,648</td>
 <td class="numeric">72.03</td>
 <td class="numeric">9.65</td>
 <td class="numeric">14.26</td>
 </tr>,
 <tr>
 <td class="name">Burkina Faso</td>
 <td>Africa<br/>
 <small>(North West)</small></td>
 <td>Ouagadougou</td>
 <td>West African CFA franc</td>
 <td class="numeric">13,227,840</td>
 <td class="numeric">274,000</td>
 <td class="numeric">48</td>
 <td class="numeric">5,171</td>
 <td class="numeric">48.45</td>
 <td class="numeric">45.62</td>
 <td class="numeric">15.92</td>
 </tr>,
 <tr>
 <td class="name">Burundi</td>
 <td>Africa<br/>
 <small>(Central East)</small></td>
 <td>Bujumbura</td>
 <td>Burundian franc</td>
 <td class="numeric">7,547,515</td>
 <td class="numeric">27,834</td>
 <td class="numeric">271</td>
 <td class="numeric">800</td>
 <td class="numeric">50.29</td>
 <td class="numeric">42.22</td>
 <td class="numeric">13.79</td>
 </tr>,
 <tr>
 <td class="name">Cambodia</td>
 <td>Asia<br/>
 <small>(South East)</small></td>
 <td>Phnom Penh</td>
 <td>Cambodian riel</td>
 <td class="numeric">14,071,010</td>
 <td class="numeric">181,035</td>
 <td class="numeric">78</td>
 <td class="numeric">5,391</td>
 <td class="numeric">58.92</td>
 <td class="numeric">26.90</td>
 <td class="numeric">9.15</td>
 </tr>,
 <tr>
 <td class="name">Cameroon</td>
 <td>Africa<br/>
 <small>(Central West)</small></td>
 <td>Yaoundé</td>
 <td>Central African CFA franc</td>
 <td class="numeric">16,321,860</td>
 <td class="numeric">475,442</td>
 <td class="numeric">34</td>
 <td class="numeric">16,985</td>
 <td class="numeric">50.89</td>
 <td class="numeric">33.89</td>
 <td class="numeric">13.63</td>
 </tr>,
 <tr>
 <td class="name">Canada</td>
 <td>North America<br/>
 <small>(North Central)</small></td>
 <td>Ottawa</td>
 <td>Canadian dollar</td>
 <td class="numeric">32,268,240</td>
 <td class="numeric">9,970,610</td>
 <td class="numeric">3</td>
 <td class="numeric">1,115,192</td>
 <td class="numeric">80.22</td>
 <td class="numeric">10.78</td>
 <td class="numeric">7.73</td>
 </tr>,
 <tr>
 <td class="name">Cape Verde</td>
 <td>Africa<br/>
 <small>(North West)</small></td>
 <td>Praia</td>
 <td>Cape Verdean escudo</td>
 <td class="numeric">506,807</td>
 <td class="numeric">4,033</td>
 <td class="numeric">126</td>
 <td class="numeric">1,024</td>
 <td class="numeric">70.45</td>
 <td class="numeric">24.87</td>
 <td class="numeric">6.62</td>
 </tr>,
 <tr>
 <td class="name">Central African Republic</td>
 <td>Africa<br/>
 <small>(Central)</small></td>
 <td>Bangui</td>
 <td>Central African CFA franc</td>
 <td class="numeric">4,037,747</td>
 <td class="numeric">622,984</td>
 <td class="numeric">6</td>
 <td class="numeric">1,369</td>
 <td class="numeric">43.39</td>
 <td class="numeric">33.91</td>
 <td class="numeric">18.81</td>
 </tr>,
 <tr>
 <td class="name">Chad</td>
 <td>Africa<br/>
 <small>(North Central)</small></td>
 <td>N'Djamena</td>
 <td>Central African CFA franc</td>
 <td class="numeric">9,748,931</td>
 <td class="numeric">1,284,000</td>
 <td class="numeric">7</td>
 <td class="numeric">5,469</td>
 <td class="numeric">47.18</td>
 <td class="numeric">45.73</td>
 <td class="numeric">16.71</td>
 </tr>,
 <tr>
 <td class="name">Chile</td>
 <td>South America<br/>
 <small>(South West)</small></td>
 <td>Valparaíso</td>
 <td>Chilean peso</td>
 <td class="numeric">16,295,100</td>
 <td class="numeric">756,096</td>
 <td class="numeric">22</td>
 <td class="numeric">115,248</td>
 <td class="numeric">76.58</td>
 <td class="numeric">15.23</td>
 <td class="numeric">5.76</td>
 </tr>,
 <tr>
 <td class="name">China, People's Republic of</td>
 <td>Asia<br/>
 <small>(Central East)</small></td>
 <td>Beijing</td>
 <td>Chinese yuan (renminbi)</td>
 <td class="numeric">1,315,844,000</td>
 <td class="numeric">9,596,961</td>
 <td class="numeric">137</td>
 <td class="numeric">2,228,862</td>
 <td class="numeric">72.27</td>
 <td class="numeric">13.25</td>
 <td class="numeric">6.94</td>
 </tr>,
 <tr>
 <td class="name">Colombia</td>
 <td>South America<br/>
 <small>(North West)</small></td>
 <td>Bogotá</td>
 <td>Colombian peso</td>
 <td class="numeric">45,600,240</td>
 <td class="numeric">1,138,914</td>
 <td class="numeric">40</td>
 <td class="numeric">122,309</td>
 <td class="numeric">71.72</td>
 <td class="numeric">20.48</td>
 <td class="numeric">5.59</td>
 </tr>,
 <tr>
 <td class="name">Comoros</td>
 <td>Africa<br/>
 <small>(South East)</small></td>
 <td>Moroni</td>
 <td>Comorian franc</td>
 <td class="numeric">797,902</td>
 <td class="numeric">2,235</td>
 <td class="numeric">357</td>
 <td class="numeric">382</td>
 <td class="numeric">61.96</td>
 <td class="numeric">36.93</td>
 <td class="numeric">8.40</td>
 </tr>,
 <tr>
 <td class="name">Congo, Democratic Republic of the</td>
 <td>Africa<br/>
 <small>(Central)</small></td>
 <td>Kinshasa</td>
 <td>Congolese franc</td>
 <td class="numeric">57,548,740</td>
 <td class="numeric">2,344,858</td>
 <td class="numeric">25</td>
 <td class="numeric">6,974</td>
 <td class="numeric">51.10</td>
 <td class="numeric">43.69</td>
 <td class="numeric">13.54</td>
 </tr>,
 <tr>
 <td class="name">Congo, Republic of the</td>
 <td>Africa<br/>
 <small>(Central West)</small></td>
 <td>Brazzaville</td>
 <td>Central African CFA franc</td>
 <td class="numeric">3,998,904</td>
 <td class="numeric">342,000</td>
 <td class="numeric">11</td>
 <td class="numeric">5,091</td>
 <td class="numeric">52.26</td>
 <td class="numeric">42.57</td>
 <td class="numeric">13.30</td>
 </tr>,
 <tr>
 <td class="name">Costa Rica</td>
 <td>North America<br/>
 <small>(South East)</small></td>
 <td>San José</td>
 <td>Costa Rican colón</td>
 <td class="numeric">4,327,228</td>
 <td class="numeric">51,100</td>
 <td class="numeric">85</td>
 <td class="numeric">19,432</td>
 <td class="numeric">76.84</td>
 <td class="numeric">18.32</td>
 <td class="numeric">4.33</td>
 </tr>,
 <tr>
 <td class="name">Croatia</td>
 <td>Europe<br/>
 <small>(South East)</small></td>
 <td>Zagreb</td>
 <td>Croatian kuna</td>
 <td class="numeric">4,551,338</td>
 <td class="numeric">56,538</td>
 <td class="numeric">81</td>
 <td class="numeric">37,412</td>
 <td class="numeric">74.45</td>
 <td class="numeric">9.61</td>
 <td class="numeric">11.38</td>
 </tr>,
 <tr>
 <td class="name">Cuba</td>
 <td>North America<br/>
 <small>(South East)</small></td>
 <td>Havana</td>
 <td>Cuban convertible peso;<br/>Cuban peso</td>
 <td class="numeric">11,269,400</td>
 <td class="numeric">110,861</td>
 <td class="numeric">102</td>
 <td class="numeric">19,356</td>
 <td class="numeric">77.23</td>
 <td class="numeric">11.89</td>
 <td class="numeric">7.19</td>
 </tr>,
 <tr>
 <td class="name">Cyprus</td>
 <td>Asia<br/>
 <small>(Central West)</small></td>
 <td>Nicosia</td>
 <td>Cypriot pound</td>
 <td class="numeric">264,172</td>
 <td class="numeric">3,355</td>
 <td class="numeric">78</td>
 <td class="numeric">15,418</td>
 <td class="numeric">77.82</td>
 <td class="numeric">12.56</td>
 <td class="numeric">7.64</td>
 </tr>,
 <tr>
 <td class="name">Czech Republic</td>
 <td>Europe<br/>
 <small>(Central)</small></td>
 <td>Prague</td>
 <td>Czech koruna</td>
 <td class="numeric">10,219,600</td>
 <td class="numeric">78,866</td>
 <td class="numeric">130</td>
 <td class="numeric">122,345</td>
 <td class="numeric">76.02</td>
 <td class="numeric">10.40</td>
 <td class="numeric">10.54</td>
 </tr>,
 <tr>
 <td class="name">Denmark</td>
 <td>Europe<br/>
 <small>(North Central)</small></td>
 <td>Copenhagen</td>
 <td>Danish krone</td>
 <td class="numeric">5,430,590</td>
 <td class="numeric">43,094</td>
 <td class="numeric">126</td>
 <td class="numeric">254,401</td>
 <td class="numeric">77.79</td>
 <td class="numeric">11.13</td>
 <td class="numeric">10.43</td>
 </tr>,
 <tr>
 <td class="name">Djibouti</td>
 <td>Africa<br/>
 <small>(North East)</small></td>
 <td>Djibouti City</td>
 <td>Djiboutian franc</td>
 <td class="numeric">793,078</td>
 <td class="numeric">23,200</td>
 <td class="numeric">34</td>
 <td class="numeric">702</td>
 <td class="numeric">43.10</td>
 <td class="numeric">39.53</td>
 <td class="numeric">19.39</td>
 </tr>,
 <tr>
 <td class="name">Dominica</td>
 <td>North America<br/>
 <small>(South East)</small></td>
 <td>Roseau</td>
 <td>East Caribbean dollar</td>
 <td class="numeric">78,940</td>
 <td class="numeric">751</td>
 <td class="numeric">105</td>
 <td class="numeric">279</td>
 <td class="numeric">74.65</td>
 <td class="numeric">15.27</td>
 <td class="numeric">6.81</td>
 </tr>,
 <tr>
 <td class="name">Dominican Republic</td>
 <td>North America<br/>
 <small>(South East)</small></td>
 <td>Santo Domingo</td>
 <td>Dominican peso</td>
 <td class="numeric">8,894,907</td>
 <td class="numeric">48,671</td>
 <td class="numeric">183</td>
 <td class="numeric">28,303</td>
 <td class="numeric">71.44</td>
 <td class="numeric">23.22</td>
 <td class="numeric">5.73</td>
 </tr>,
 <tr>
 <td class="name">Ecuador</td>
 <td>South America<br/>
 <small>(North West)</small></td>
 <td>Quito</td>
 <td>United States dollar</td>
 <td class="numeric">13,228,420</td>
 <td class="numeric">283,561</td>
 <td class="numeric">47</td>
 <td class="numeric">36,244</td>
 <td class="numeric">76.21</td>
 <td class="numeric">22.29</td>
 <td class="numeric">4.24</td>
 </tr>,
 <tr>
 <td class="name">Egypt</td>
 <td>Africa<br/>
 <small>(North East)</small></td>
 <td>Cairo</td>
 <td>Egyptian pound</td>
 <td class="numeric">74,032,880</td>
 <td class="numeric">1,001,449</td>
 <td class="numeric">74</td>
 <td class="numeric">89,336</td>
 <td class="numeric">71.00</td>

Regardons maintenant la structure d'une de nos balises avec plus de détail.

In [5]:
all_data[1]

<tr>
<td class="name">Abkhazia</td>
<td>Asia<br/>
<small>(Central West)</small></td>
<td>Sukhumi</td>
<td>Georgian lari;<br/>Russian ruble</td>
<td class="numeric">216,000</td>
<td class="numeric">8,600</td>
<td class="numeric">25</td>
<td class="numeric">-</td>
<td class="numeric">-</td>
<td class="numeric">-</td>
<td class="numeric">-</td>
</tr>

Les informations que nous voulons extraire de situent dans les balises `td`.

In [15]:
import re 

data = []
for country in all_data[1:]:
    temp_data = []
    content = country.find_all("td")
    for line in content:
        temp_data.append(re.split('>|<',str(line))[2])      
    data.append(temp_data)

print(data)

[['Abkhazia', 'Asia', 'Sukhumi', 'Georgian lari;', '216,000', '8,600', '25', '-', '-', '-', '-'], ['Afghanistan', 'Asia', 'Kabul', 'Afghan afghani', '29,863,010', '652,090', '46', '7,168', '42.90', '46.60', '20.75'], ['Albania', 'Europe', 'Tirana', 'Albanian lek', '3,129,678', '28,748', '109', '8,379', '77.24', '15.11', '5.12'], ['Algeria', 'Africa', 'Algiers', 'Algerian dinar', '32,853,800', '2,381,741', '13', '102,257', '73.00', '17.14', '4.60'], ['Andorra', 'Europe', 'Andorra la Vella', 'Euro', '67,151', '468', '143', '960', '83.51', '8.71', '6.07'], ['Angola', 'Africa', 'Luanda', 'Angolan kwanza', '15,941,390', '1,246,700', '12', '28,038', '38.43', '45.11', '24.50'], ['Antigua and Barbuda', 'North America', "St. John's", 'East Caribbean dollar', '81,479', '442', '184', '905', '71.90', '16.93', '5.44'], ['Argentina', 'South America', 'Buenos Aires', 'Argentine peso', '38,747,150', '2,780,400', '13', '183,309', '75.91', '16.73', '7.56'], ['Armenia', 'Asia', 'Yerevan', 'Armenian dram', '3,016,312', '29,800', '101', '4,903', '71.55', '12.07', '8.16'], ['Australia', 'Oceana', 'Canberra', 'Australian dollar', '20,155,130', '7,741,220', '2', '700,672', '81.01', '12.14', '7.44'], ['Austria', 'Europe', 'Vienna', 'Euro', '8,189,444', '83,858', '98', '304,527', '79.07', '8.74', '9.70'], ['Azerbaijan', 'Asia', 'Baku', 'Azerbaijani manat', '8,410,801', '86,600', '97', '12,561', '63.35', '20.74', '9.86'], ['Bahamas', 'North America', 'Nassau', 'Bahamian dollar', '323,063', '13,878', '23', '5,502', '65.54', '17.57', '8.97'], ['Bahrain', 'Asia', 'Manama', 'Bahraini dinar', '726,617', '694', '1,047', '12,995', '74.23', '17.80', '4.08'], ['Bangladesh', 'Asia', 'Dhaka', 'Bangladeshi taka', '141,822,300', '143,998', '985', '59,958', '62.08', '29.80', '8.40'], ['Barbados', 'North America', 'Bridgetown', 'Barbadian dollar', '269,556', '430', '627', '2,976', '72.59', '12.71', '8.74'], ['Belarus', 'Europe', 'Minsk', 'Belarusian ruble', '9,755,106', '207,600', '47', '29,566', '68.72', '11.16', '14.15'], ['Belgium', 'Europe', 'Brussels', 'Euro', '10,419,050', '30,528', '341', '364,735', '78.77', '10.38', '10.22'], ['Belize', 'North America', 'Belmopan', 'Belize dollar', '269,736', '22,966', '11', '1,105', '68.44', '28.84', '5.65'], ['Benin', 'Africa', 'Cotonou', 'West African CFA franc', '8,438,853', '112,622', '75', '4,287', '52.66', '38.85', '12.49'], ['Bhutan', 'Asia', 'Thimphu', 'Bhutanese ngultrum;', '2,162,546', '47,000', '46', '840', '54.39', '33.65', '12.94'], ['Bolivia', 'South America', 'La Paz', 'Bolivian boliviano', '9,182,015', '1,098,581', '8', '9,334', '65.50', '23.30', '7.64'], ['Bosnia and Herzegovina', 'Europe', 'Sarajevo', 'Convertible mark', '3,907,074', '51,197', '76', '9,369', '78.00', '8.77', '8.08'], ['Botswana', 'Africa', 'Gaborone', 'Botswana pula', '1,764,926', '581,730', '3', '9,350', '33.87', '23.08', '29.36'], ['Brazil', 'South America', 'Brasília', 'Brazilian real', '186,404,900', '8,514,877', '22', '794,098', '71.69', '16.56', '6.15'], ['Brunei', 'Asia', 'Bandar Seri Begawan', 'Brunei dollar;', '373,819', '5,765', '65', '9,531', '74.80', '18.79', '3.42'], ['Bulgaria', 'Europe', 'Sofia', 'Bulgarian lev', '7,725,965', '110,912', '70', '26,648', '72.03', '9.65', '14.26'], ['Burkina Faso', 'Africa', 'Ouagadougou', 'West African CFA franc', '13,227,840', '274,000', '48', '5,171', '48.45', '45.62', '15.92'], ['Burundi', 'Africa', 'Bujumbura', 'Burundian franc', '7,547,515', '27,834', '271', '800', '50.29', '42.22', '13.79'], ['Cambodia', 'Asia', 'Phnom Penh', 'Cambodian riel', '14,071,010', '181,035', '78', '5,391', '58.92', '26.90', '9.15'], ['Cameroon', 'Africa', 'Yaoundé', 'Central African CFA franc', '16,321,860', '475,442', '34', '16,985', '50.89', '33.89', '13.63'], ['Canada', 'North America', 'Ottawa', 'Canadian dollar', '32,268,240', '9,970,610', '3', '1,115,192', '80.22', '10.78', '7.73'], ['Cape Verde', 'Africa', 'Praia', 'Cape Verdean escudo', '506,807', '4,033', '126', '1,024', '70.45', '24.87', '6.62'], ['Central African Republic', 'Africa', 'Bangui', 'Central African CFA franc', '4,037,747', '622,984', '6', '1,369', '43.39', '33.91', '18.81'], ['Chad', 'Africa', "N'Djamena", 'Central African CFA franc', '9,748,931', '1,284,000', '7', '5,469', '47.18', '45.73', '16.71'], ['Chile', 'South America', 'Valparaíso', 'Chilean peso', '16,295,100', '756,096', '22', '115,248', '76.58', '15.23', '5.76'], ["China, People's Republic of", 'Asia', 'Beijing', 'Chinese yuan (renminbi)', '1,315,844,000', '9,596,961', '137', '2,228,862', '72.27', '13.25', '6.94'], ['Colombia', 'South America', 'Bogotá', 'Colombian peso', '45,600,240', '1,138,914', '40', '122,309', '71.72', '20.48', '5.59'], ['Comoros', 'Africa', 'Moroni', 'Comorian franc', '797,902', '2,235', '357', '382', '61.96', '36.93', '8.40'], ['Congo, Democratic Republic of the', 'Africa', 'Kinshasa', 'Congolese franc', '57,548,740', '2,344,858', '25', '6,974', '51.10', '43.69', '13.54'], ['Congo, Republic of the', 'Africa', 'Brazzaville', 'Central African CFA franc', '3,998,904', '342,000', '11', '5,091', '52.26', '42.57', '13.30'], ['Costa Rica', 'North America', 'San José', 'Costa Rican colón', '4,327,228', '51,100', '85', '19,432', '76.84', '18.32', '4.33'], ['Croatia', 'Europe', 'Zagreb', 'Croatian kuna', '4,551,338', '56,538', '81', '37,412', '74.45', '9.61', '11.38'], ['Cuba', 'North America', 'Havana', 'Cuban convertible peso;', '11,269,400', '110,861', '102', '19,356', '77.23', '11.89', '7.19'], ['Cyprus', 'Asia', 'Nicosia', 'Cypriot pound', '264,172', '3,355', '78', '15,418', '77.82', '12.56', '7.64'], ['Czech Republic', 'Europe', 'Prague', 'Czech koruna', '10,219,600', '78,866', '130', '122,345', '76.02', '10.40', '10.54'], ['Denmark', 'Europe', 'Copenhagen', 'Danish krone', '5,430,590', '43,094', '126', '254,401', '77.79', '11.13', '10.43'], ['Djibouti', 'Africa', 'Djibouti City', 'Djiboutian franc', '793,078', '23,200', '34', '702', '43.10', '39.53', '19.39'], ['Dominica', 'North America', 'Roseau', 'East Caribbean dollar', '78,940', '751', '105', '279', '74.65', '15.27', '6.81'], ['Dominican Republic', 'North America', 'Santo Domingo', 'Dominican peso', '8,894,907', '48,671', '183', '28,303', '71.44', '23.22', '5.73'], ['Ecuador', 'South America', 'Quito', 'United States dollar', '13,228,420', '283,561', '47', '36,244', '76.21', '22.29', '4.24'], ['Egypt', 'Africa', 'Cairo', 'Egyptian pound', '74,032,880', '1,001,449', '74', '89,336', '71.00', '22.94', '5.26'], ['El Salvador', 'North America', 'San Salvador', 'Salvadoran colón;', '6,880,951', '21,041', '327', '16,974', '71.22', '26.61', '5.85'], ['Equatorial Guinea', 'Africa', 'Malabo', 'Central African CFA franc', '503,519', '28,051', '18', '3,231', '49.70', '35.59', '15.04'], ['Eritrea', 'Africa', 'Asmara', 'Eritrean nakfa', '4,401,357', '117,600', '37', '986', '58.47', '34.33', '9.87'], ['Estonia', 'Europe', 'Tallinn', 'Estonian kroon', '1,329,697', '45,100', '29', '13,107', '71.77', '10.04', '13.21'], ['Ethiopia', 'Africa', 'Addis Ababa', 'Ethiopian birr', '77,430,700', '1,104,300', '70', '11,174', '48.83', '37.98', '15.06'], ['Fiji', 'Oceana', 'Suva', 'Fijian dollar', '847,706', '18,274', '46', '2,810', '69.53', '22.55', '5.65'], ['Finland', 'Europe', 'Helsinki', 'Euro', '5,249,060', '338,145', '15', '193,176', '78.50', '10.45', '9.79'], ['France', 'Europe', 'Paris', 'Euro', '60,495,540', '551,500', '110', '2,110,185', '79.73', '11.99', '9.08'], ['Gabon', 'Africa', 'Libreville', 'Central African CFA franc', '1,383,841', '267,668', '5', '8,055', '55.02', '36.16', '12.03'], ['Gambia', 'Africa', 'Banjul', 'Gambian dalasi', '1,517,079', '11,295', '134', '461', '53.75', '39.37', '12.52'], ['Georgia', 'Asia', 'Tbilisi', 'Georgian lari', '4,474,404', '69,700', '64', '6,395', '75.88', '10.41', '9.09'], ['Germany', 'Europe', 'Berlin', 'Euro', '82,689,210', '357,022', '232', '2,781,900', '78.80', '8.25', '10.55'], ['Ghana', 'Africa', 'Accra', 'Ghanaian cedi', '22,112,810', '238,533', '93', '10,695', '58.47', '30.52', '9.91'], ['Greece', 'Europe', 'Athens', 'Euro', '11,119,890', '131,957', '84', '213,698', '79.24', '9.68', '10.15'], ['Grenada', 'North America', "St. George's", 'East Caribbean dollar', '102,924', '344', '260', '454', '64.53', '22.08', '7.17'], ['Guatemala', 'North America', 'Guatemala City', 'Guatemalan quetzal', '12,599,060', '108,889', '116', '31,683', '69.06', '29.88', '5.30'], ['Guinea', 'Africa', 'Conakry', 'Guinean franc', '9,402,098', '245,857', '38', '2,689', '49.36', '41.76', '15.63'], ['Guinea-Bissau', 'Africa', 'Bissau', 'West African CFA franc', '1,586,344', '36,125', '44', '301', '46.61', '37.22', '16.73'], ['Guyana', 'South America', 'Georgetown', 'Guyanese dollar', '751,218', '214,969', '3', '783', '65.50', '18.28', '8.32'], ['Haiti', 'North America', 'Port-au-Prince', 'Haitian gourde', '8,527,777', '27,750', '307', '4,245', '52.92', '36.44', '12.34'], ['Honduras', 'North America', 'Tegucigalpa', 'Honduran lempira', '7,204,723', '112,088', '64', '7,976', '69.30', '28.24', '5.25'], ['Hungary', 'Europe', 'Budapest', 'Hungarian forint', '10,097,730', '93,032', '109', '109,154', '72.40', '9.72', '13.19'], ['Iceland', 'Europe', 'Reykjavík', 'Icelandic króna', '294,561', '103,000', '2', '15,036', '80.31', '13.64', '6.68'], ['India', 'Asia', 'New Delhi', 'Indian rupee', '1,103,371,000', '3,287,263', '336', '785,468', '64.35', '22.01', '8.28'], ['Indonesia', 'Asia', 'Jakarta', 'Indonesian rupiah', '222,781,500', '1,904,569', '117', '287,217', '69.57', '20.34', '6.25'], ['Iran', 'Asia', 'Tehran', 'Iranian rial', '69,515,210', '1,648,195', '42', '196,343', '69.96', '17.00', '5.55'], ['Iraq', 'Asia', 'Baghdad', 'Iraqi dinar', '28,807,190', '438,317', '66', '12,602', '68.70', '31.98', '5.49'], ['Ireland', 'Europe', 'Dublin', 'Euro', '4,147,901', '70,273', '59', '196,388', '77.56', '14.45', '7.85'], ['Israel', 'Asia', 'Jerusalem', 'Israeli new sheqel', '6,724,564', '22,145', '304', '123,434', '79.46', '17.97', '6.18'], ['Italy', 'Europe', 'Rome', 'Euro', '58,092,740', '301,318', '193', '1,723,044', '79.81', '8.72', '10.30'], ['Ivory Coast', 'Africa', 'Abidjan', 'West African CFA franc', '18,153,870', '322,463', '56', '16,055', '48.62', '35.11', '14.94'], ['Jamaica', 'North America', 'Kingston', 'Jamaican dollar', '2,650,713', '10,991', '241', '9,696', '73.33', '20.82', '6.47'], ['Japan', 'Asia', 'Tokyo', 'Japanese yen', '128,084,700', '377,873', '339', '4,505,912', '81.25', '9.37', '8.95'], ['Jordan', 'Asia', 'Amman', 'Jordanian dinar', '5,702,776', '89,342', '64', '12,861', '78.40', '21.25', '2.63'], ['Kazakhstan', 'Asia', 'Astana', 'Kazakhstani tenge', '14,825,110', '2,724,900', '5', '56,088', '66.55', '16.00', '9.46'], ['Kenya', 'Africa', 'Nairobi', 'Kenyan shilling', '34,255,720', '580,367', '59', '17,977', '47.99', '39.72', '14.65'], ['Kiribati', 'Oceana', 'South Tarawa', 'Australian dollar;', '99,350', '726', '137', '76', '61.71', '30.65', '8.37'], ['Korea, North', 'Asia', 'Pyongyang', 'North Korean won', '22,487,660', '120,538', '187', '5,997', '71.37', '15.54', '7.05'], ['Korea, South', 'Asia', 'Seoul', 'South Korean won', '48,846,823', '99,538', '480', '787,624', '76.85', '10.00', '5.72'], ['Kuwait', 'Asia', 'Kuwait City', 'Kuwaiti dinar', '2,686,873', '17,818', '151', '74,658', '77.03', '21.94', '2.42'], ['Kyrgyzstan', 'Asia', 'Bishkek', 'Kyrgyzstani som', '5,263,794', '199,900', '26', '2,441', '68.16', '22.80', '7.13'], ['Laos', 'Asia', 'Vientiane', 'Lao kip', '5,924,145', '236,800', '25', '2,855', '55.08', '35.49', '11.83'], ['Latvia', 'Europe', 'Riga', 'Latvian lats', '2,306,988', '64,600', '36', '15,771', '71.05', '9.24', '13.70'], ['Lebanon', 'Asia', 'Beirut', 'Lebanese lira', '3,576,818', '10,400', '344', '22,210', '72.63', '18.52', '6.24'], ['Lesotho', 'Africa', 'Maseru', 'Lesotho loti;', '1,794,769', '30,355', '59', '1,453', '34.47', '24.75', '28.67'], ['Liberia', 'Africa', 'Monrovia', 'Liberian dollar', '3,283,267', '111,369', '29', '548', '38.89', '44.77', '23.93'], ['Libya', 'Africa', 'Tripoli', 'Libyan dinar', '5,853,452', '1,759,540', '3', '38,756', '76.50', '26.49', '3.48'], ['Liechtenstein', 'Europe', 'Vaduz', 'Swiss franc', '34,521', '160', '216', '1,315', '79.68', '10.21', '7.06'], ['Lithuania', 'Europe', 'Vilnius', 'Lithuanian litas', '3,431,033', '65,300', '53', '25,495', '73.97', '8.75', '10.92'], ['Luxembourg', 'Europe', 'Luxembourg City', 'Euro', '464,904', '2,586', '180', '33,779', '78.89', '11.94', '8.41'], ['Macedonia, Former Yugoslavia Republic of', 'Europe', 'Skopje', 'Macedonian denar', '2,034,060', '25,713', '79', '5,762', '73.73', '12.02', '8.73'], ['Madagascar', 'Africa', 'Antananarivo', 'Malagasy ariary', '18,605,920', '587,041', '32', '5,040', '56.95', '41.41', '11.35'], ['Malawi', 'Africa', 'Lilongwe', 'Malawian kwacha', '12,883,940', '118,484', '109', '2,072', '41.43', '43.13', '19.63'], ['Malaysia', 'Asia', 'Putrajaya', 'Malaysian ringgit', '25,347,370', '329,847', '77', '130,143', '72.24', '22.86', '5.06'], ['Maldives', 'Asia', 'Malé', 'Maldivian rufiyaa', '329,198', '298', '1,105', '817', '64.06', '34.81', '7.24'], ['Mali', 'Africa', 'Bamako', 'West African CFA franc', '13,518,420', '1,240,192', '10', '5,098', '48.64', '49.82', '17.23'], ['Malta', 'Europe', 'Valletta', 'Maltese lira', '401,630', '316', '1,271', '5,570', '79.01', '10.22', '8.00'], ['Marshall Islands', 'Oceana', 'Majuro', 'United States dollar', '61,963', '181', '342', '144', '70.01', '33.05', '4.88'], ['Mauritania', 'Africa', 'Nouakchott', 'Mauritanian ouguiya', '3,068,742', '1,025,520', '3', '1,888', '52.73', '40.99', '12.44'], ['Mauritius', 'Africa', 'Port Louis', 'Mauritian rupee', '1,244,663', '2,040', '610', '6,447', '72.38', '15.43', '6.83'], ['Mexico', 'North America', 'Mexico City', 'Mexican peso', '107,029,400', '1,958,201', '55', '768,438', '75.19', '20.69', '4.73'], ['Micronesia, Federated States of', 'Oceana', 'Palikir', 'Micronesian dollar;', '110,487', '702', '157', '232', '69.75', '24.68', '4.87'], ['Moldova', 'Europe', 'Chisinau', 'Moldovan leu', '4,205,747', '33,851', '124', '2,906', '65.18', '15.70', '12.79'], ['Monaco', 'Europe', 'Monaco', 'Euro', '35,253', '1', '23,660', '847', '79.69', '9.19', '12.71'], ['Mongolia', 'Asia', 'Ulaanbaatar', 'Mongolian tugrug', '2,646,487', '1,564,116', '1', '1,880', '64.52', '21.59', '7.03'], ['Montenegro', 'Europe', 'Podgorica', 'Euro', '630,548', '14,026', '45', '27,059', '74.73', '12.60', '9.20'], ['Morocco', 'Africa', 'Rabat', 'Moroccan dirham', '31,478,460', '446,550', '70', '51,745', '70.66', '21.98', '5.64'], ['Mozambique', 'Africa', 'Maputo', 'Mozambican metical', '19,792,300', '801,590', '25', '6,630', '40.32', '35.18', '20.99'], ['Myanmar (Burma)', 'Asia', 'Naypyidaw', 'Myanmar kyat', '50,519,490', '676,578', '75', '12,151', '60.70', '17.91', '9.85'], ['Nagorno-Karabakh', 'Asia', 'Khankendi', 'Armenian dram;', '145,000', '4,400', '33', '-', '-', '-', '-'], ['Namibia', 'Africa', 'Windhoek', 'Namibian dollar;', '2,031,252', '824,292', '2', '6,126', '43.93', '24.32', '18.36'], ['Nauru', 'Oceana', 'None', 'Australian dollar;', '13,635', '21', '649', '368', '62.73', '24.76', '6.82'], ['Nepal', 'Asia', 'Kathmandu', 'Nepalese rupee', '27,132,630', '147,181', '184', '7,346', '59.80', '30.98', '9.47'], ['Netherlands, The', 'Europe', 'Amsterdam', 'Euro', '16,299,170', '41,528', '392', '594,755', '78.96', '10.90', '8.68'], ['New Zealand', 'Oceana', 'Wellington', 'New Zealand dollar', '4,028,384', '270,534', '14', '109,041', '78.81', '13.76', '7.53'], ['Nicaragua', 'North America', 'Managua', 'Nicaraguan córdoba', '5,486,685', '130,000', '42', '4,911', '70.33', '24.51', '4.49'], ['Niger', 'Africa', 'Niamey', 'West African CFA franc', '13,956,980', '1,267,000', '11', '3,405', '43.50', '50.73', '21.19'], ['Nigeria', 'Africa', 'Abuja', 'Nigerian naira', '131,529,700', '923,768', '142', '98,951', '46.74', '40.43', '17.18'], ['Norway', 'Europe', 'Oslo', 'Norwegian krone', '4,620,275', '385,155', '12', '283,920', '79.54', '11.46', '9.45'], ['Oman', 'Asia', 'Muscat', 'Omani rial', '2,566,981', '309,500', '8', '24,284', '73.13', '36.24', '3.86'], ['Pakistan', 'Europe', 'Islamabad', 'Pakistani rupee', '157,935,100', '796,095', '198', '110,732', '63.00', '29.74', '8.45'], ['Palau', 'Oceana', 'Melekeok', 'Palauan dollar;', '19,949', '459', '43', '145', '70.14', '18.03', '6.85'], ['Panama', 'North America', 'Panama City', 'Panamanian balboa;', '3,231,502', '75,517', '43', '15,467', '75.25', '21.74', '5.28'], ['Papua New Guinea', 'Oceana', 'Port Moresby', 'Papua New Guinean kina', '5,887,138', '462,840', '12', '4,731', '64.93', '29.36', '7.37'], ['Paraguay', 'South America', 'Asunción', 'Paraguayan guaraní', '6,158,259', '406,752', '15', '8,152', '74.89', '29.10', '4.53'], ['Peru', 'South America', 'Lima', 'Peruvian nuevo sol', '27,968,240', '1,285,216', '22', '78,431', '69.53', '20.48', '6.26'], ['Philippines', 'Asia', 'Manila', 'Philippine peso', '83,054,480', '300,000', '277', '98,306', '69.91', '24.89', '5.47'], ['Poland', 'Europe', 'Warsaw', 'Polish zloty', '38,529,560', '312,685', '123', '299,151', '74.74', '9.85', '9.84'], ['Portugal', 'Europe', 'Lisbon', 'Euro', '10,494,500', '91,982', '114', '173,085', '77.53', '10.72', '10.43'], ['Qatar', 'Asia', 'Doha', 'Qatari riyal', '812,842', '11,000', '74', '28,451', '73.67', '15.56', '4.61'], ['Romania', 'Europe', 'Bucharest', 'Romanian leu', '21,711,470', '238,391', '91', '98,559', '71.35', '10.70', '11.74'], ['Russia', 'Asia', 'Moscow', 'Russian ruble', '143,201,600', '17,098,242', '8', '763,720', '67.10', '9.95', '14.52'], ['Rwanda', 'Africa', 'Kigali', 'Rwandan franc', '9,037,690', '26,338', '343', '2,131', '46.96', '40.37', '16.32'], ['Saint Kitts and Nevis', 'North America', 'Basseterre', 'East Caribbean dollar', '42,696', '261', '164', '453', '72.15', '18.02', '8.47'], ['Saint Lucia', 'North America', 'Castries', 'East Caribbean dollar', '160,765', '539', '298', '825', '73.61', '19.68', '5.12'], ['Saint Vincent and the Grenadines', 'North America', 'Kingstown', 'East Caribbean dollar', '119,051', '388', '307', '428', '73.62', '16.18', '6.00'], ['Samoa', 'Oceana', 'Apia', 'Samoan tala', '184,984', '2,831', '65', '399', '70.72', '16.43', '6.54'], ['San Marino', 'Europe', 'San Marino', 'Euro', '28,117', '61', '461', '478', '81.71', '10.02', '8.07'], ['São Tomé and Príncipe', 'Africa', 'São Tomé', 'São Tomé and Príncipe dobra', '156,523', '964', '162', '57', '66.99', '40.25', '6.68'], ['Saudi Arabia', 'Asia', 'Riyadh', 'Saudi riyal', '24,573,100', '2,149,690', '11', '309,778', '75.46', '29.34', '2.62'], ['Senegal', 'Africa', 'Dakar', 'West African CFA franc', '11,658,170', '196,722', '59', '8,318', '58.90', '32.78', '9.59'], ['Serbia', 'Europe', 'Belgrade', 'Serbian dinar', '9,396,411', '88,361', '106', '24,058', '74.73', '-', '-'], ['Seychelles', 'Africa', 'Victoria', 'Seychellois rupee', '80,654', '455', '177', '694', '71.82', '16.03', '6.34'], ['Sierra Leone', 'Africa', 'Freetown', 'Sierra Leonean leone', '5,525,478', '71,740', '77', '1,193', '39.87', '45.76', '23.43'], ['Singapore', 'Asia', 'Singapore', 'Brunei dollar;', '4,483,900', '699', '6,208', '116,764', '81.71', '9.34', '4.16'], ['Slovakia', 'Europe', 'Bratislava', 'Slovak koruna', '5,400,908', '49,033', '110', '46,412', '74.50', '10.65', '9.43'], ['Slovenia', 'Europe', 'Ljubljana', 'Euro', '1,966,814', '20,256', '97', '34,030', '76.14', '8.98', '10.22'], ['Solomon Islands', 'Oceana', 'Honiara', 'Solomon Islands dollar', '477,742', '28,896', '16', '286', '72.66', '30.01', '3.98'], ['Somalia', 'Africa', 'Mogadishu', 'Somali shilling', '8,227,826', '637,657', '12', '1,132', '48.09', '45.13', '16.97'], ['Somaliland', 'Africa', 'Hargeisa', 'Somaliland shilling', '3,500,000', '137,600', '25', '-', '-', '-', '-'], ['South Africa', 'Africa', 'Bloemfontein', 'South African rand', '47,431,830', '1,221,037', '39', '240,152', '43.27', '18.20', '21.32'], ['South Ossetia', 'Asia', 'Tskhinvali', 'Georgian lari;', '70,000', '3,900', '18', '-', '-', '-', '-'], ['Spain', 'Europe', 'Madrid', 'Euro', '43,064,190', '505,992', '85', '1,12

Nous voulons maintenant ajouter les labels des colonnes à notre liste de listes.

In [16]:
header = []
content = all_data[0].find_all("th")
for line in content:
    header.append(re.split('>|<',str(line))[2]) 

header

['Name',
 'Location',
 'Capital city',
 'Currency',
 'Population',
 'Area',
 'Pop. density',
 'GDP (nominal)',
 'Life exp.',
 'Birth rate',
 'Death rate']

In [17]:
data.insert(0, header)
data

[['Name',
  'Location',
  'Capital city',
  'Currency',
  'Population',
  'Area',
  'Pop. density',
  'GDP (nominal)',
  'Life exp.',
  'Birth rate',
  'Death rate'],
 ['Abkhazia',
  'Asia',
  'Sukhumi',
  'Georgian lari;',
  '216,000',
  '8,600',
  '25',
  '-',
  '-',
  '-',
  '-'],
 ['Afghanistan',
  'Asia',
  'Kabul',
  'Afghan afghani',
  '29,863,010',
  '652,090',
  '46',
  '7,168',
  '42.90',
  '46.60',
  '20.75'],
 ['Albania',
  'Europe',
  'Tirana',
  'Albanian lek',
  '3,129,678',
  '28,748',
  '109',
  '8,379',
  '77.24',
  '15.11',
  '5.12'],
 ['Algeria',
  'Africa',
  'Algiers',
  'Algerian dinar',
  '32,853,800',
  '2,381,741',
  '13',
  '102,257',
  '73.00',
  '17.14',
  '4.60'],
 ['Andorra',
  'Europe',
  'Andorra la Vella',
  'Euro',
  '67,151',
  '468',
  '143',
  '960',
  '83.51',
  '8.71',
  '6.07'],
 ['Angola',
  'Africa',
  'Luanda',
  'Angolan kwanza',
  '15,941,390',
  '1,246,700',
  '12',
  '28,038',
  '38.43',
  '45.11',
  '24.50'],
 ['Antigua and Barbuda',
  'North America',
  "St. John's",
  'East Caribbean dollar',
  '81,479',
  '442',
  '184',
  '905',
  '71.90',
  '16.93',
  '5.44'],
 ['Argentina',
  'South America',
  'Buenos Aires',
  'Argentine peso',
  '38,747,150',
  '2,780,400',
  '13',
  '183,309',
  '75.91',
  '16.73',
  '7.56'],
 ['Armenia',
  'Asia',
  'Yerevan',
  'Armenian dram',
  '3,016,312',
  '29,800',
  '101',
  '4,903',
  '71.55',
  '12.07',
  '8.16'],
 ['Australia',
  'Oceana',
  'Canberra',
  'Australian dollar',
  '20,155,130',
  '7,741,220',
  '2',
  '700,672',
  '81.01',
  '12.14',
  '7.44'],
 ['Austria',
  'Europe',
  'Vienna',
  'Euro',
  '8,189,444',
  '83,858',
  '98',
  '304,527',
  '79.07',
  '8.74',
  '9.70'],
 ['Azerbaijan',
  'Asia',
  'Baku',
  'Azerbaijani manat',
  '8,410,801',
  '86,600',
  '97',
  '12,561',
  '63.35',
  '20.74',
  '9.86'],
 ['Bahamas',
  'North America',
  'Nassau',
  'Bahamian dollar',
  '323,063',
  '13,878',
  '23',
  '5,502',
  '65.54',
  '17.57',
  '8.97'],
 ['Bahrain',
  'Asia',
  'Manama',
  'Bahraini dinar',
  '726,617',
  '694',
  '1,047',
  '12,995',
  '74.23',
  '17.80',
  '4.08'],
 ['Bangladesh',
  'Asia',
  'Dhaka',
  'Bangladeshi taka',
  '141,822,300',
  '143,998',
  '985',
  '59,958',
  '62.08',
  '29.80',
  '8.40'],
 ['Barbados',
  'North America',
  'Bridgetown',
  'Barbadian dollar',
  '269,556',
  '430',
  '627',
  '2,976',
  '72.59',
  '12.71',
  '8.74'],
 ['Belarus',
  'Europe',
  'Minsk',
  'Belarusian ruble',
  '9,755,106',
  '207,600',
  '47',
  '29,566',
  '68.72',
  '11.16',
  '14.15'],
 ['Belgium',
  'Europe',
  'Brussels',
  'Euro',
  '10,419,050',
  '30,528',
  '341',
  '364,735',
  '78.77',
  '10.38',
  '10.22'],
 ['Belize',
  'North America',
  'Belmopan',
  'Belize dollar',
  '269,736',
  '22,966',
  '11',
  '1,105',
  '68.44',
  '28.84',
  '5.65'],
 ['Benin',
  'Africa',
  'Cotonou',
  'West African CFA franc',
  '8,438,853',
  '112,622',
  '75',
  '4,287',
  '52.66',
  '38.85',
  '12.49'],
 ['Bhutan',
  'Asia',
  'Thimphu',
  'Bhutanese ngultrum;',
  '2,162,546',
  '47,000',
  '46',
  '840',
  '54.39',
  '33.65',
  '12.94'],
 ['Bolivia',
  'South America',
  'La Paz',
  'Bolivian boliviano',
  '9,182,015',
  '1,098,581',
  '8',
  '9,334',
  '65.50',
  '23.30',
  '7.64'],
 ['Bosnia and Herzegovina',
  'Europe',
  'Sarajevo',
  'Convertible mark',
  '3,907,074',
  '51,197',
  '76',
  '9,369',
  '78.00',
  '8.77',
  '8.08'],
 ['Botswana',
  'Africa',
  'Gaborone',
  'Botswana pula',
  '1,764,926',
  '581,730',
  '3',
  '9,350',
  '33.87',
  '23.08',
  '29.36'],
 ['Brazil',
  'South America',
  'Brasília',
  'Brazilian real',
  '186,404,900',
  '8,514,877',
  '22',
  '794,098',
  '71.69',
  '16.56',
  '6.15'],
 ['Brunei',
  'Asia',
  'Bandar Seri Begawan',
  'Brunei dollar;',
  '373,819',
  '5,765',
  '65',
  '9,531',
  '74.80',
  '18.79',
  '3.42'],
 ['Bulgaria',
  'Europe',
  'Sofia',
  'Bulgarian lev',
  '7,725,965',
  '110,912',
  '70',
  '26,648',
  '72.03',
  '9.65',
  '14.26'],
 ['Burkina Faso',
  'Africa',
  'Ouagadougou',
  'West African CFA franc',
  '13,227,840',
  '274,000',
  '48',
  '5,171',
  '48.45',
  '45.62',
  '15.92'],
 ['Burundi',
  'Africa',
  'Bujumbura',
  'Burundian franc',
  '7,547,515',
  '27,834',
  '271',
  '800',
  '50.29',
  '42.22',
  '13.79'],
 ['Cambodia',
  'Asia',
  'Phnom Penh',
  'Cambodian riel',
  '14,071,010',
  '181,035',
  '78',
  '5,391',
  '58.92',
  '26.90',
  '9.15'],
 ['Cameroon',
  'Africa',
  'Yaoundé',
  'Central African CFA franc',
  '16,321,860',
  '475,442',
  '34',
  '16,985',
  '50.89',
  '33.89',
  '13.63'],
 ['Canada',
  'North America',
  'Ottawa',
  'Canadian dollar',
  '32,268,240',
  '9,970,610',
  '3',
  '1,115,192',
  '80.22',
  '10.78',
  '7.73'],
 ['Cape Verde',
  'Africa',
  'Praia',
  'Cape Verdean escudo',
  '506,807',
  '4,033',
  '126',
  '1,024',
  '70.45',
  '24.87',
  '6.62'],
 ['Central African Republic',
  'Africa',
  'Bangui',
  'Central African CFA franc',
  '4,037,747',
  '622,984',
  '6',
  '1,369',
  '43.39',
  '33.91',
  '18.81'],
 ['Chad',
  'Africa',
  "N'Djamena",
  'Central African CFA franc',
  '9,748,931',
  '1,284,000',
  '7',
  '5,469',
  '47.18',
  '45.73',
  '16.71'],
 ['Chile',
  'South America',
  'Valparaíso',
  'Chilean peso',
  '16,295,100',
  '756,096',
  '22',
  '115,248',
  '76.58',
  '15.23',
  '5.76'],
 ["China, People's Republic of",
  'Asia',
  'Beijing',
  'Chinese yuan (renminbi)',
  '1,315,844,000',
  '9,596,961',
  '137',
  '2,228,862',
  '72.27',
  '13.25',
  '6.94'],
 ['Colombia',
  'South America',
  'Bogotá',
  'Colombian peso',
  '45,600,240',
  '1,138,914',
  '40',
  '122,309',
  '71.72',
  '20.48',
  '5.59'],
 ['Comoros',
  'Africa',
  'Moroni',
  'Comorian franc',
  '797,902',
  '2,235',
  '357',
  '382',
  '61.96',
  '36.93',
  '8.40'],
 ['Congo, Democratic Republic of the',
  'Africa',
  'Kinshasa',
  'Congolese franc',
  '57,548,740',
  '2,344,858',
  '25',
  '6,974',
  '51.10',
  '43.69',
  '13.54'],
 ['Congo, Republic of the',
  'Africa',
  'Brazzaville',
  'Central African CFA franc',
  '3,998,904',
  '342,000',
  '11',
  '5,091',
  '52.26',
  '42.57',
  '13.30'],
 ['Costa Rica',
  'North America',
  'San José',
  'Costa Rican colón',
  '4,327,228',
  '51,100',
  '85',
  '19,432',
  '76.84',
  '18.32',
  '4.33'],
 ['Croatia',
  'Europe',
  'Zagreb',
  'Croatian kuna',
  '4,551,338',
  '56,538',
  '81',
  '37,412',
  '74.45',
  '9.61',
  '11.38'],
 ['Cuba',
  'North America',
  'Havana',
  'Cuban convertible peso;',
  '11,269,400',
  '110,861',
  '102',
  '19,356',
  '77.23',
  '11.89',
  '7.19'],
 ['Cyprus',
  'Asia',
  'Nicosia',
  'Cypriot pound',
  '264,172',
  '3,355',
  '78',
  '15,418',
  '77.82',
  '12.56',
  '7.64'],
 ['Czech Republic',
  'Europe',
  'Prague',
  'Czech koruna',
  '10,219,600',
  '78,866',
  '130',
  '122,345',
  '76.02',
  '10.40',
  '10.54'],
 ['Denmark',
  'Europe',
  'Copenhagen',
  'Danish krone',
  '5,430,590',
  '43,094',
  '126',
  '254,401',
  '77.79',
  '11.13',
  '10.43'],
 ['Djibouti',
  'Africa',
  'Djibouti City',
  'Djiboutian franc',
  '793,078',
  '23,200',
  '34',
  '702',
  '43.10',
  '39.53',
  '19.39'],
 ['Dominica',
  'North America',
  'Roseau',
  'East Caribbean dollar',
  '78,940',
  '751',
  '105',
  '279',
  '74.65',
  '15.27',
  '6.81'],
 ['Dominican Republic',
  'North America',
  'Santo Domingo',
  'Dominican peso',
  '8,894,907',
  '48,671',
  '183',
  '28,303',
  '71.44',
  '23.22',
  '5.73'],
 ['Ecuador',
  'South America',
  'Quito',
  'United States dollar',
  '13,228,420',
  '283,561',
  '47',
  '36,244',
  '76.21',
  '22.29',
  '4.24'],
 ['Egypt',
  'Africa',
  'Cairo',
  'Egyptian pound',
  '74,032,880',
  '1,001,449',
  '74',
  '89,336',
  '71.00',
  '22.94',
  '5.26'],
 ['El Salvador',
  'North America',
  'San Salvador',
  'Salvadoran colón;',
  '6,880,951',
  '21,041',
  '327',
  '16,974',
  '71.22',
  '26.61',
  '5.85'],
 ['Equatorial Guinea',
  'Africa',
  'Malabo',
  'Central African CFA franc',
  '503,519',
  '28,051',
  '18',
  '3,231',
  '49.70',
  '35.59',
  '15.04'],
 ['Eritrea',
  'Africa',
  'Asmara',
  'Eritrean nakfa',
  '4,401,357',
  '117,600',
  '37',
  '986',
  '58.47',
  '34.33',
  '9.87'],
 ['Estonia',
  'Europe',
  'Tallinn',
  'Estonian kroon',
  '1,329,697',
  '45,100',
  '29',
  '13,107',
  '71.77',
  '10.04',
  '13.21'],
 ['Ethiopia',
  'Africa',
  'Addis Ababa',
  'Ethiopian birr',
  '77,430,700',
  '1,104,300',
  '70',
  '11,174',
  '48.83',
  '37.98',
  '15.06'],
 ['Fiji',
  'Oceana',
  'Suva',
  'Fijian dollar',
  '847,706',
  '18,274',
  '46',
  '2,810',
  '69.53',
  '22.55',
  '5.65'],
 ['Finland',
  'Europe',
  'Helsinki',
  'Euro',
  '5,249,060',
  '338,145',
  '15',
  '193,176',
  '78.50',
  '10.45',
  '9.79'],
 ['France',
  'Europe',
  'Paris',
  'Euro',
  '60,495,540',
  '551,500',
  '110',
  '2,110,185',
  '79.73',
  '11.99',
  '9.08'],
 ['Gabon',
  'Africa',
  'Libreville',
  'Central African CFA franc',
  '1,383,841',
  '267,668',
  '5',
  '8,055',
  '55.02',
  '36.16',
  '12.03'],
 ['Gambia',
  'Africa',
  'Banjul',
  'Gambian dalasi',
  '1,517,079',
  '11,295',
  '134',
  '461',
  '53.75',
  '39.37',
  '12.52'],
 ['Georgia',
  'Asia',
  'Tbilisi',
  'Georgian lari',
  '4,474,404',
  '69,700',
  '64',
  '6,395',
  '75.88',
  '10.41',
  '9.09'],
 ['Germany',
  'Europe',
  'Berlin',
  'Euro',
  '82,689,210',
  '357,022',
  '232',
  '2,781,900',
  '78.80',
  '8.25',
  '10.55'],
 ['Ghana',
  'Africa',
  'Accra',
  'Ghanaian cedi',
  '22,112,810',
  '238,533',
  '93',
  '10,695',
  '58.47',
  '30.52',
  '9.91'],
 ['Greece',
  'Europe',
  'Athens',
  'Euro',
  '11,119,890',
  '131,957',
  '84',
  '213,698',
  '79.24',
  '9.68',
  '10.15'],
 ['Grenada',
  'North America',
  "St. George's",
  'East Caribbean dollar',
  '102,924',
  '344',
  '260',
  '454',
  '64.53',
  '22.08',
  '7.17'],
 ['Guatemala',
  'North America',
  'Guatemala City',
  'Guatemalan quetzal',
  '12,599,060',
  '108,889',
  '116',
  '31,683',
  '69.06',
  '29.88',
  '5.30'],
 ['Guinea',
  'Africa',
  'Conakry',
  'Guinean franc',
  '9,402,098',
  '245,857',
  '38',
  '2,689',
  '49.36',
  '41.76',
  '15.63'],
 ['Guinea-Bissau',
  'Africa',
  'Bissau',
  'West African CFA franc',
  '1,586,344',
  '36,125',
  '44',
  '301',
  '46.61',
  '37.22',
  '16.73'],
 ['Guyana',
  'South America',
  'Georgetown',
  'Guyanese dollar',
  '751,218',
  '214,969',
  '3',
  '783',
  '65.50',
  '18.28',
  '8.32'],
 ['Haiti',
  'North America',
  'Port-au-Prince',
  'Haitian gourde',
  '8,527,777',
  '27,750',
  '307',
  '4,245',
  '52.92',
  '36.44',
  '12.34'],
 ['Honduras',
  'North America',
  'Tegucigalpa',
  'Honduran lempira',
  '7,204,723',
  '112,088',
  '64',
  '7,976',
  '69.30',
  '28.24',
  '5.25'],
 ['Hungary',
  'Europe',
  'Budapest',
  'Hungarian forint',
  '10,097,730',
  '93,032',
  '109',
  '109,154',
  '72.40',
  '9.72',
  '13.19'],
 ['Iceland',
  'Europe',
  'Reykjavík',
  'Icelandic króna',
  '294,561',
  '103,000',
  '2',
  '15,036',
  '80.31',
  '13.64',
  '6.68'],
 ['India',
  'Asia',
  'New Delhi',
  'Indian rupee',
  '1,103,371,000',
  '3,287,263',
  '336',
  '785,468',
  '64.35',
  '22.01',
  '8.28'],
 ['Indonesia',
  'Asia',
  'Jakarta',
  'Indonesian rupiah',
  '222,781,500',
  '1,904,569',
  '117',
  '287,217',
  '69.57',
  '20.34',
  '6.25'],
 ['Iran',
  'Asia',
  'Tehran',
  'Iranian rial',
  '69,515,210',
  '1,648,195',
  '42',
  '196,343',
  '69.96',
  '17.00',
  '5.55'],
 ['Iraq',
  'Asia',
  'Baghdad',
  'Iraqi dinar',
  '28,807,190',
  '438,317',
  '66',
  '12,602',
  '68.70',
  '31.98',
  '5.49'],
 ['Ireland',
  'Europe',
  'Dublin',
  'Euro',
  '4,147,901',
  '70,273',
  '59',
  '196,388',
  '77.56',
  '14.45',
  '7.85'],
 ['Israel',
  'Asia',
  'Jerusalem',
  'Israeli new sheqel',
  '6,724,564',
  '22,145',
  '304',
  '123,434',
  '79.46',
  '17.97',
  '6.18'],
 ['Italy',
  'Europe',
  'Rome',
  'Euro',
  '58,092,740',
  '301,318',
  '193',
  '1,723,044',
  '79.81',
  '8.72',
  '10.30'],
 ['Ivory Coast',
  'Africa',
  'Abidjan',
  'West African CFA franc',
  '18,153,870',
  '322,463',
  '56',
  '16,055',
  '48.62',
  '35.11',
  '14.94'],
 ['Jamaica',
  'North America',
  'Kingston',
  'Jamaican dollar',
  '2,650,713',
  '10,991',
  '241',
  '9,696',
  '73.33',
  '20.82',
  '6.47'],
 ['Japan',
  'Asia',
  'Tokyo',
  'Japanese yen',
  '128,084,700',
  '377,873',
  '339',
  '4,505,912',
  '81.25',
  '9.37',
  '8.95'],
 ['Jordan',
  'Asia',
  'Amman',
  'Jordanian dinar',
  '5,702,776',
  '89,342',
  '64',
  '12,861',
  '78.40',
  '21.25',
  '2.63'],
 ['Kazakhstan',
  'Asia',
  'Astana',
  'Kazakhstani tenge',
  '14,825,110',
  '2,724,900',
  '5',
  '56,088',
  '66.55',
  '16.00',
  '9.46'],
 ['Kenya',
  'Africa',
  'Nairobi',
  'Kenyan shilling',
  '34,255,720',
  '580,367',
  '59',
  '17,977',
  '47.99',
  '39.72',
  '14.65'],
 ['Kiribati',
  'Oceana',
  'South Tarawa',
  'Australian dollar;',
  '99,350',
  '726',
  '137',
  '76',
  '61.71',
  '30.65',
  '8.37'],
 ['Korea, North',
  'Asia',
  'Pyongyang',
  'North Korean won',
  '22,487,660',
  '120,538',
  '187',
  '5,997',
  '71.37',
  '15.54',
  '7.05'],
 ['Korea, South',
  'Asia',
  'Seoul',
  'South Korean won',
  '48,846,823',
  '99,538',
  '480',
  '787,624',
  '76.85',
  '10.00',
  '5.72'],
 ['Kuwait',
  'Asia',
  'Kuwait City',
  'Kuwaiti dinar',
  '2,686,873',
  '17,818',
  '151',
  '74,658',
  '77.03',
  '21.94',
  '2.42'],
 ['Kyrgyzstan',
  'Asia',
  'Bishkek',
  'Kyrgyzstani som',
  '5,263,794',
  '199,900',
  '26',
  '2,441',
  '68.16',
  '22.80',
  '7.13'],
 ['Laos',
  'Asia',
  'Vientiane',
  'Lao kip',
  '5,924,145',
  '236,800',
  '25',
  '2,855',
  '55.08',
  '35.49',
  '11.83'],
 ['Latvia',
  'Europe',
  'Riga',
  'Latvian lats',
  '2,306,988',
  '64,600',
  '36',
  '15,771',
  '71.05',
  '9.24',
  '13.70'],
 ['Lebanon',
  'Asia',
  'Beirut',
  'Lebanese lira',
  '3,576,818',
  '10,400',
  '344',
  '22,210',
  '72.63',
  '18.52',
  '6.24'],
 ['Lesotho',
  'Africa',
  'Maseru',
  'Lesotho loti;',
  '1,794,769',
  '30,355',
  '59',
  '1,453',
  '34.47',
  '24.75',
  '28.67'],
 ['Liberia',
  'Africa',
  'Monrovia',
  'Liberian dollar',
  '3,283,267',
  '111,369',
  '29',
  '548',
  '38.89',
  '44.77',
  '23.93'],
 ['Libya',
  'Africa',
  'Tripoli',
  'Libyan dinar',
  '5,853,452',
  '1,759,540',
  '3',
  '38,756',
  '76.50',
  '26.49',
  '3.48'],
 ['Liechtenstein',
  'Europe',
  'Vaduz',
  'Swiss franc',
  '34,521',
  '160',
  '216',
  '1,315',
  '79.68',
  '10.21',
  '7.06'],
 ['Lithuania',
  'Europe',
  'Vilnius',
  'Lithuanian litas',
  '3,431,033',
  '65,300',
  '53',
  '25,495',
  '73.97',
  '8.75',
  '10.92'],
 ['Luxembourg',
  'Europe',
  'Luxembourg City',
  'Euro',
  '464,904',
  '2,586',
  '180',
  '33,779',
  '78.89',
  '11.94',
  '8.41'],
 ['Macedonia, Former Yugoslavia Republic of',
  'Europe',
  'Skopje',
  'Macedonian denar',
  '2,034,060',
  '25,713',
  '79',
  '5,762',
  '73.73',
  '12.02',
  '8.73'],
 ['Madagascar',
  'Africa',
  'Antananarivo',
  'Malagasy ariary',
  '18,605,920',
  '587,041',
  '32',
  '5,040',
  '56.95',
  '41.41',
  '11.35'],
 ['Malawi',
  'Africa',
  'Lilongwe',
  'Malawian kwacha',
  '12,883,940',
  '118,484',
  '109',
  '2,072',
  '41.43',
  '43.13',
  '19.63'],
 ['Malaysia',
  'Asia',
  'Putrajaya',
  'Malaysian ringgit',
  '25,347,370',
  '329,847',
  '77',
  '130,143',
  '72.24',
  '22.86',
  '5.06'],
 ['Maldives',
  'Asia',
  'Malé',
  'Maldivian rufiyaa',
  '329,198',
  '298',
  '1,105',
  '817',
  '64.06',
  '34.81',
  '7.24'],
 ['Mali',
  'Africa',
  'Bamako',
  'West African CFA franc',
  '13,518,420',
  '1,240,192',
  '10',
  '5,098',
  '48.64',
  '49.82',
  '17.23'],
 ['Malta',
  'Europe',
  'Valletta',
  'Maltese lira',
  '401,630',
  '316',
  '1,271',
  '5,570',
  '79.01',
  '10.22',
  '8.00'],
 ['Marshall Islands',
  'Oceana',
  'Majuro',
  'United States dollar',
  '61,963',
  '181',
  '342',
  '144',
  '70.01',
  '33.05',
  '4.88'],
 ['Mauritania',
  'Africa',
  'Nouakchott',
  'Mauritanian ouguiya',
  '3,068,742',
  '1,025,520',
  '3',
  '1,888',
  '52.73',
  '40.99',
  '12.44'],
 ['Mauritius',
  'Africa',
  'Port Louis',
  'Mauritian rupee',
  '1,244,663',
  '2,040',
  '610',
  '6,447',
  '72.38',
  '15.43',
  '6.83'],
 ['Mexico',
  'North America',
  'Mexico City',
  'Mexican peso',
  '107,029,400',
  '1,958,201',
  '55',
  '768,438',
  '75.19',
  '20.69',
  '4.73'],
 ['Micronesia, Federated States of',
  'Oceana',
  'Palikir',
  'Micronesian dollar;',
  '110,487',
  '702',
  '157',
  '232',
  '69.75',
  '24.68',
  '4.87'],
 ['Moldova',
  'Europe',
  'Chisinau',
  'Moldovan leu',
  '4,205,747',
  '33,851',
  '124',
  '2,906',
  '65.18',
  '15.70',
  '12.79'],
 ['Monaco',
  'Europe',
  'Monaco',
  'Euro',
  '35,253',
  '1',
  '23,660',
  '847',
  '79.69',
  '9.19',
  '12.71'],
 ['Mongolia',
  'Asia',
  'Ulaanbaatar',
  'Mongolian tugrug',
  '2,646,487',
  '1,564,116',
  '1',
  '1,880',
  '64.52',
  '21.59',
  '7.03'],
 ['Montenegro',
  'Europe',
  'Podgorica',
  'Euro',
  '630,548',
  '14,026',
  '45',
  '27,059',
  '74.73',
  '12.60',
  '9.20'],
 ['Morocco',
  'Africa',
  'Rabat',
  'Moroccan dirham',
  '31,478,460',
  '446,550',
  '70',
  '51,745',
  '70.66',
  '21.98',
  '5.64'],
 ['Mozambique',
  'Africa',
  'Maputo',
  'Mozambican metical',
  '19,792,300',
  '801,590',
  '25',
  '6,630',
  '40.32',
  '35.18',
  '20.99'],
 ['Myanmar (Burma)',
  'Asia',
  'Naypyidaw',
  'Myanmar kyat',
  '50,519,490',
  '676,578',
  '75',
  '12,151',
  '60.70',
  '17.91',
  '9.85'],
 ['Nagorno-Karabakh',
  'Asia',
  'Khankendi',
  'Armenian dram;',
  '145,000',
  '4,400',
  '33',
  '-',
  '-',
  '-',
  '-'],
 ['Namibia',
  'Africa',
  'Windhoek',
  'Namibian dollar;',
  '2,031,252',
  '824,292',
  '2',
  '6,126',
  '43.93',
  '24.32',
  '18.36'],
 ['Nauru',
  'Oceana',
  'None',
  'Australian dollar;',
  '13,635',
  '21',
  '649',
  '368',
  '62.73',
  '24.76',
  '6.82'],
 ['Nepal',
  'Asia',
  'Kathmandu',
  'Nepalese rupee',
  '27,132,630',
  '147,181',
  '184',
  '7,346',
  '59.80',
  '30.98',
  '9.47'],
 ['Netherlands, The',
  'Europe',
  'Amsterdam',
  'Euro',
  '16,299,170',
  '41,528',
  '392',
  '594,755',
  '78.96',
  '10.90',
  '8.68'],
 ['New Zealand',
  'Oceana',
  'Wellington',
  'New Zealand dollar',
  '4,028,384',
  '270,534',
  '14',
  '109,041',
  '78.81',
  '13.76',
  '7.53'],
 ['Nicaragua',
  'North America',
  'Managua',
  'Nicaraguan córdoba',
  '5,486,685',
  '130,000',
  '42',
  '4,911',
  '70.33',
  '24.51',
  '4.49'],
 ['Niger',
  'Africa',
  'Niamey',
  'West African CFA franc',
  '13,956,980',
  '1,267,000',
  '11',
  '3,405',
  '43.50',
  '50.73',
  '21.19'],
 ['Nigeria',
  'Africa',
  'Abuja',
  'Nigerian naira',
  '131,529,700',
  '923,768',
  '142',
  '98,951',
  '46.74',
  '40.43',
  '17.18'],
 ['Norway',
  'Europe',
  'Oslo',
  'Norwegian krone',
  '4,620,275',
  '385,155',
  '12',
  '283,920',
  '79.54',
  '11.46',
  '9.45'],
 ['Oman',
  'Asia',
  'Muscat',
  'Omani rial',
  '2,566,981',
  '309,500',
  '8',
  '24,284',
  '73.13',
  '36.24',
  '3.86'],
 ['Pakistan',
  'Europe',
  'Islamabad',
  'Pakistani rupee',
  '157,935,100',
  '796,095',
  '198',
  '110,732',
  '63.00',
  '29.74',
  '8.45'],
 ['Palau',
  'Oceana',
  'Melekeok',
  'Palauan dollar;',
  '19,949',
  '459',
  '43',
  '145',
  '70.14',
  '18.03',
  '6.85'],
 ['Panama',
  'North America',
  'Panama City',
  'Panamanian balboa;',
  '3,231,502',
  '75,517',
  '43',
  '15,467',
  '75.25',
  '21.74',
  '5.28'],
 ['Papua New Guinea',
  'Oceana',
  'Port Moresby',
  'Papua New Guinean kina',
  '5,887,138',
  '462,840',
  '12',
  '4,731',
  '64.93',
  '29.36',
  '7.37'],
 ['Paraguay',
  'South America',
  'Asunción',
  'Paraguayan guaraní',
  '6,158,259',
  '406,752',
  '15',
  '8,152',
  '74.89',
  '29.10',
  '4.53'],
 ['Peru',
  'South America',
  'Lima',
  'Peruvian nuevo sol',
  '27,968,240',
  '1,285,216',
  '22',
  '78,431',
  '69.53',
  '20.48',
  '6.26'],
 ['Philippines',
  'Asia',
  'Manila',
  'Philippine peso',
  '83,054,480',
  '300,000',
  '277',
  '98,306',
  '69.91',
  '24.89',

In [25]:
import pandas as pd

df = pd.DataFrame.from_records(data[1:], columns=data[0])
df

,Name,Location,Capital city,Currency,Population,Area,Pop. density,GDP (nominal),Life exp.,Birth rate,Death rate
0,Abkhazia,Asia,Sukhumi,Georgian lari;,"216,000","8,600",25,-,-,-,-
1,Afghanistan,Asia,Kabul,Afghan afghani,"29,863,010","652,090",46,"7,168",42.90,46.60,20.75
2,Albania,Europe,Tirana,Albanian lek,"3,129,678","28,748",109,"8,379",77.24,15.11,5.12
3,Algeria,Africa,Algiers,Algerian dinar,"32,853,800","2,381,741",13,"102,257",73.00,17.14,4.60
4,Andorra,Europe,Andorra la Vella,Euro,"67,151",468,143,960,83.51,8.71,6.07
...,...,...,...,...,...,...,...,...,...,...,...
194,Venezuela,South America,Caracas,Venezuelan bolívar,"26,749,110","912,050",29,"138,857",74.31,18.71,4.90
195,Vietnam,Asia,Hanoi,Vietnamese d?ng,"84,238,230","331,689",254,"52,408",70.61,16.86,6.20
196,Yemen,Asia,Sanaá,Yemeni rial,"20,974,660","527,968",40,"14,452",61.75,42.89,8.53
197,Zambia,Africa,Lusaka,Zambian kwacha,"11,668,460","752,618",15,"7,257",39.70,41.00,20.23
198,Zimbabwe,Africa,Harare,Zimbabwean dollar,"13,009,530","390,757",33,"3,364",37.82,28.01,21.92

In [26]:
#df.to_csv('pays.csv')

**Exercice:** Faites un dataframe du tableau de la page suivante http://doheth.co.uk/info/us-states.php

## Scraping de Tweets

Il existe plusieurs moyens pour récupérer des tweets: l'API Twitter, commande bash snscrape, librairie python Tweepy, etc ...

Nous allons juste voir rapidement comment utiliser `snscrape` https://medium.com/dataseries/how-to-scrape-millions-of-tweets-using-snscrape-195ee3594721

Essayons de récupérer des tweets ayant le mot "marvel" seulement sur 2 jours.

In [27]:
%%bash
snscrape --jsonl --progress --max-results 50000 --since 2021-07-27 twitter-search 'lang:fr marvel until:2021-07-28' > tweets.json

Scraping, 100 results so far
Scraping, 200 results so far
Scraping, 300 results so far
Scraping, 400 results so far
Scraping, 500 results so far
Scraping, 600 results so far
Scraping, 700 results so far

In [29]:
twitter_data = pd.read_json('tweets.json', lines=True)
twitter_data

,url,date,content,renderedContent,id,user,outlinks,tcooutlinks,replyCount,retweetCount,...,lang,source,sourceUrl,sourceLabel,media,retweetedTweet,quotedTweet,mentionedUsers,coordinates,place
0,https://twitter.com/ununoctiium/status/1420171...,2021-07-27 23:58:18+00:00,@LuluciferGrt Et cumberbatch est définitivemen...,@LuluciferGrt Et cumberbatch est définitivemen...,1420171722171551744,"{'username': 'ununoctiium', 'displayname': 'ju...",[],[],1,0,...,fr,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,None,NaN,None,"[{'username': 'LuluciferGrt', 'displayname': '...",None,None
1,https://twitter.com/inquieto_Romeo/status/1420...,2021-07-27 23:55:19+00:00,- mas é q a marvel... https://t.co/4x2UEA8f11,- mas é q a marvel... https://t.co/4x2UEA8f11,1420170971219124224,"{'username': 'inquieto_Romeo', 'displayname': ...",[],[],0,0,...,fr,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,[{'previewUrl': 'https://pbs.twimg.com/media/E...,NaN,None,None,None,None
2,https://twitter.com/the_abyssion/status/142016...,2021-07-27 23:36:30+00:00,@NetflixFR Ça y est ils nous font une marvel,@NetflixFR Ça y est ils nous font une marvel,1420166236168761347,"{'username': 'the_abyssion', 'displayname': 't...",[],[],1,0,...,fr,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,None,NaN,None,"[{'username': 'NetflixFR', 'displayname': 'Net...",None,None
3,https://twitter.com/benialloush/status/1420165...,2021-07-27 23:35:20+00:00,Demain dans le train jsp si je regarde un Marv...,Demain dans le train jsp si je regarde un Marv...,1420165942550609923,"{'username': 'benialloush', 'displayname': 'ch...",[],[],0,0,...,fr,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,None,NaN,None,None,None,None
4,https://twitter.com/zougagmehd/status/14201641...,2021-07-27 23:28:05+00:00,@Marvel_Fit Ca se voit de ouf que c’est fake,@Marvel_Fit Ca se voit de ouf que c’est fake,1420164115406929921,"{'username': 'zougagmehd', 'displayname': 'Zou...",[],[],0,0,...,fr,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,None,NaN,None,"[{'username': 'Marvel_Fit', 'displayname': 'Ma...",None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,https://twitter.com/7faat/status/1419813908995...,2021-07-27 00:16:29+00:00,J’ai envie de recommencer tout les films de Ma...,J’ai envie de recommencer tout les films de Ma...,1419813908995575809,"{'username': '7faat', 'displayname': 'Fat❤️‍🔥'...",[],[],1,1,...,fr,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,None,NaN,None,None,None,None
769,https://twitter.com/orlandead/status/141981238...,2021-07-27 00:10:25+00:00,Puis jsp pourquoi les fans de Marvel ont peur ...,Puis jsp pourquoi les fans de Marvel ont peur ...,1419812381039996929,"{'username': 'orlandead', 'displayname': 'TRAN...",[],[],0,0,...,fr,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,None,NaN,None,None,None,None
770,https://twitter.com/alwaysxhalo/status/1419812...,2021-07-27 00:09:08+00:00,favourite marvel character?,favourite marvel character?,1419812059743756296,"{'username': 'alwaysxhalo', 'displayname': 'Jo...",[],[],1,0,...,fr,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,None,NaN,None,None,None,None
771,https://twitter.com/sahvasylui/status/14198114...,2021-07-27 00:06:33+00:00,@ksnawej c’est le pire marvel pour l’instant,@ksnawej c’est le pire marvel pour l’instant,1419811410381578250,"{'username': 'sahvasylui', 'displayname': 'DLK...",[],[],1,0,...,fr,"<a href=""http://twitter.com/download/iphone"" r...",http://twitter.com/download/iphone,Twitter for iPhone,None,NaN,None,"[{'username': 'ksnawej', 'displayname': 'nana'...",None,None
772,https://twitter.com/Aspissim/status/1419810230...,2021-07-27 00:01:52+00:00,En 2035 Batman et Superman seront dans le doma...,En 2035 Batman et Superman seront dans le doma...,1419810230926520325,"{'username': 'Aspissim', 'displayname': 'Aspis...",[],[],0,0,...,fr,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,None,NaN,None,None,None,None

## Data Storytelling

![title](DataStorytelling.png)

Je vous invite à regarder le site suivant qui démontrent parfaitement l'idée de raconter une histoire avec des données:

https://pudding.cool

## A vous de jouer !

Maintenant à vous de trouver un dataset et une question à laquelle vous voulez répondre pour votre projet !